### ISSUE TITLE
suggestions for update on Unlimted by izj

### ISSUE THREAD

**Issue by izjgod** [Unlimited-WoW/BugTracker#1]
by izj suggestion for fixses/nerf/balance/buffs/god items removed"
all of thes arnt nesserly needed to be fixed or done anything with but, if all of them is changed the whole server would change,
for starters , , disable the meta gems with "reduce Snare/root duration by 10% 
"Fix resilience on donor gear on multipie classes? paladins donor gear 100, resilience each item
"remove. free action potion.restorative potion.living action potion, sheen of zanzan/potion of curing/purification potion"
"add Speed 100% wsg effect /zerker / healing multipie places at starting area, and instance tier 1 - 2- 3"
"change Spawn point to Tier 1 Area "add npc for starter" put sanctuary on the place"
"make all new players Spawn with Starter Gear" with starter bags in main bag" and teleporter/graccu's mince meat fruitcake"

"add up to 1.000 total all resistances for Holy resistance ON gear/Disable paladins spell penetrate "
"add new items only for paladins Healer Speller offset/jewelery Without spell Penertate"
"make speller items Class restricted"
"melee items spell restricted for Higer tiers"
"remove Shirt of the yogg-slayer It having more health than best in slot tier 12 shirt,
"vip Rings/trinket Add 1 more meta gem instead of 2x meta gems, making them worse than tier 13"
"add vip shirt/tabard/neck/Cloak"
"All pets needs Rescaling "dk/ghoul/army of the dead/worms/gorgoly,-  mage, water elements/mirrors/,-hunter Pets needs higer health And Damage taken reduced,
/druid,-  Treats,-  shaman  Feral spirit,-  priste, Shadowfiend,-  warlocks /imp/voidwalker/succbucs/felhunter/felguard,-" and other pets, most of them needs
fixed resilience / more armore / Damage reduce taken from players, and slightly buffed dmg on all pets by 15%"
"Mages Ice barrier needs too be 10. times stronger 9.3milione absorb at best in slot, mana shield 9.3mil, frost ward/fireward needs too be 6 times stronger/pyroblast nerfed 10% on players /increase fireball/frostbolt by 10% /icelance increased by 40% living bomb increased by 20% cone of cold reduced 15% arcane explosion incresed by 100% arcane blast increased by 20% arcane missiels increased by 10% frostfire bolt increased by 10%
"prieste Power word shield needs to be 3 times stronger" might need some testing firstly,Divine agies needs scaling max absorb 31.800 atm"
"hunters Chimera SHot is 100% spell Damage, thus hitting way too hard, it needs to be scaled down on players by 30-35% , aimed shot increased 20% chimeras' serpent effect doing 5 times the chimeras first hit needs too be scaled down too an agreeable Damage"
"death knights, hunger of cold needs to be fixed its not lasting full dur, Rune wepone needs to be fixed ITs Far from working correctly/and runeforge needs to be working on all wepones / anti magic zone needs to be rescaled / icebound 99.99% aka 1 auto attack 0 spell dmg, for 18 seconds and immune too stun should be scaled down too agreeable half that >_> like 50% or 40% as the glyph, Death coil's Dot unholy blight needs nerf it doing up too 7 times the death coils direct hit,it seems way to overpowred with speller items on,
- Frost fever increased by 40% plague disease increased by 50% + remove immune to disease on multipie mobs in tier 13 instance,other instances who have them too, 
"priestes Mind Blast/devour plague" needs nerf by 15% increase Pain Damage by 20% to compensate, and buff shadowfeinds dmg by multipe 2-3 x and "critical healing from dispell glyph DIsabled"
"Druids Maul/mangle/swipe Reduced by 15% on players/increase Cat's Rip/rake/shred/furious bite/swipe/and miam's Damage by 20% and add 1.5 seconds global cd on infected wounds. All healing druids have needs to be buffed by 15%- moonfire/swarm increased dmg by 10% Bear form Faerie fire REduced by 60%"
"shaman Increase Healing on Riptide by 13x times healing over time effect /healing stream totem/earthliving by 20% / INcrease Dmg ligthning bolt by 25% chain of light by 60% lava burst by 10% stormstrike by 200%  INcrease dmg on feral wolfs /healing increase dmg on magma totem by 60% increase dmg on flame shock by 10%  shocks dmg after tests /flame shock worst " frost second " earth shock first place in dmg" Healing wave increase 10% lesser healing wave increase by 25%   
-riptide direct heal increased by 15% /increase dmg on flame wave /magma totem by 100%
"warriors Increase Damage on bloodthirst/mortal strike by 10% increase cleave Damage by 15%/heroic strike/ increase Bladestorms dmg by 40% reduce dmg thunder clap by 20%"
"Paladin Increase Absorb on Sacred shield by 50% increase flash of light healing by 20% add 2 sec Cooldown on Art of war" and 1 seconds Global cd on jugment of light healing, "increase holy light healing by 25% holy shock healing by 35%" jugdgement increased Damage by 10% and Holy shock Dmg reduced by 15% Hammer of wrath needs too be scaled to normal dmg" "exoricme increased Damage by 20% and holy wrath increased damage by 50%"
"rogue cripple posions Needs 2 seconds cooldown/blade twisting talent 10 seconds cooldown/deadly Brew 2 seconds cooldown" increase rupture/garrot Damage/deadly posions/instant posions by 15% and multiate by 10%"

pvp/pve "Root Effect" from varius spells" on players/npc/monster  needs to have maximum 150mil Damage before Break first 80mil second 50mil third DR,mage water elements freeze/frost nova /icebarrier nova/ hunters /traps Root/ Druids Entangled Root/nature grasp/ ETc all Roots,

Dmg From bosses should be increased by 40% world bosses, Instance mobs should have Damage reduce by 20%, increased health by 10% add immune to slow on bosses/stun /most speller mobs in the instances /raids do 0 spell dmg , increase spell dmg on every npc with spell dmg to balance it out,
 "Arena NPc Should Be around middle of mall" 
Increase duel range by 150
Increase duration time on enchants weps for example frostbrand/windfury/spellstone by 48 hours
Zul'aman halazzi boss immortal wont go below 1 health, amani  lynx/cub/elder & Amani'shi Wind Walker & Amani Dragonhawk &Tamed Amani Crocolisk & Amani Bear Mount have no loot in zul'aman needs to be scaled & change loot table &  zul jin needs diffrent loot table perferable tokens instead of level 70 items at medium loot luck each zul'aman run is about 1.030 of each tokens + should be 1.500 multipie bosses in this raid have 2x spawns, 
.buffs for vip needs to be fixed change kings with greater blessing of sanctuary remove major agility add Gift of the wild re scaled + scaled Arcane intellect Scaled prayer of fortitude 
increase reputation Rate gained on kills by 50 and queste complete by 50 for farming titles/achivmenets
thats all i got for now, 
^^ from izj/unlimted wow regular player ,

**Comment by Draione** [comment]
Add 1v1 arena npc starting point 0raiting not 1500. Buffing PvP sets, make specific set for each class. Increasing more resil then t13 set, requirements for sets arena points with high raiting. Creating also PvP offsets,weaps. 
Making honor more valuable, add special honor vendor witch contains materials and stuff.
Shaman windfury weapon enchant dmg inc by 20% Lava Lash dmg by 15-20%. 
Death knight Icebound Fortitude has to be fixed it creates character immune to any dmg for its whole duration.
Feral druid items adding energy regeneration increase.

**Comment by izjgod** [comment]
also if you wish to have tier 14. /upgrade donor gear, i suggest that, you add 250 Player kills For Each of the tier upgrade/donor mainset/offset upgrade.

**Comment by boykevink** [comment]
we really need a nerf on the amount of meta gems a normal full geared player can get to just 3.
main 1 on each weap would be enough.
