### ISSUE TITLE
Battelground can be fun!

### ISSUE THREAD

**Issue by boykevink** [Unlimited-WoW/BugTracker#10]
ok to be honest battlegrounds que's suck on the server atm.
i mean whiles i am in warsong with just 2 aly's and no hordes,then i see  horde player que for wsg he just gets qued for another seperate wsg instesd of the empty one i am in.it would be better if  anybody that qued in for wsg will be added in an existing one that already exists because it does not have enough players.
also pls add coocking to professions npc at mall.
de we have devs for this though...

**Comment by izjgod** [comment]
i also AGree with this, Bg should be fun i think low Gear tier 1-7 can be scaled to tier 9 - IN stats 
also NO faction BG like you can become horde or allience but, when you get to the other faction, A race for that faction wil be ur Transform for example Blood elf male join BG as allience and become night elf male,'
Also Bg should benefit more from like pvp mBY some tier 14-15 only battleground tier,? or arena tier 16?
Also same tiers for vip /donation players, needs too be added ofc, Also, Random BG added with minimum 2 player to start, with normal honor per first win and second win, but Isle of conqueste disabled/altrac valley, and strand of the ancient, >leaving only Warsong gulch & arathi basin and eye of the storm, would be fun ;P

**Comment by izjgod** [comment]
also, there should be anti spawn camping system, here, where opesite faction players standing on the spawn area Aka 75 yards around the spirit resser to get a fatal debuff,
