### ISSUE TITLE
Charged leap's hitbox is excessively small compared to its visual counterpart

### ISSUE THREAD

**Issue by Flawzismad** [Unlimited-WoW/BugTracker#104]
### Description

Charged leap's hitbox is excessively small compared to its visual counterpart. Also its nearly impossible to stun people who are running around constantly with it

### Current behaviour

Upon using charged leap, stuns only apply if the target is in the inner green circle.

### Expected behaviour

Upon using charged leap, everything in the green circle should be stunned.

### Steps to Reproduce

1. Target charged leap on a player in PvP
2. Ensure the player is outside of the inner green circle
3. Use charged leap

### Attachments

<details>
<summary>View</summary>

![image](https://user-images.githubusercontent.com/33201955/152058569-56790b02-24a6-4702-83e7-cc58f34187a5.png)

![image](https://user-images.githubusercontent.com/33201955/152058627-36d5cccb-2cef-4980-8b15-6f42d11a24d0.png)
</details>

**Comment by GladiatorUW** [comment]
it uses the same spell as warriors so its not possible that it isn't "good" as warriors leap
