### ISSUE TITLE
Error con la invisibilidad del pícaro

### ISSUE THREAD

**Issue by Soulprincesss** [Unlimited-WoW/BugTracker#105]
**Description:**
sucede que el picaro no puede usar su invisibilidad luego de no atacar o ser atacado por mas de 5 segundos, todo esto ocurre en batallas.
``
**Current behaviour:**

no puedo usar invisibilidad luego de dejar de atacar a otros enemigos para asi poder volver a atacar a otro y golpearlo por sorpresa.

**Expected behaviour:**

todos sabemos que si no estas atacando a nadie y nadie te esta atacando automáticamente dejas el modo combate y puedes comer, subir a montura y en el caso del picaro usar su modo invisiblidad luego de 5 segundos pero esto no sucede asi.

**Source:**

no tengo fuentes pero es lo que me sucede a diario cada que entro a batallas

**Steps to reproduce the problem:**

1. Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.  
2. Step 2
3. Step 3

**Comment by GladiatorUW** [comment]
English please

**Comment by Soulprincesss** [comment]
Description:
It happens that the rogue cannot use his invisibility after not attacking or being attacked for more than 5 seconds, all this happens in battles.
``
actual behavior:

I can't use invisibility after I stop attacking other enemies so I can attack another one again and hit them by surprise.

Expected behavior:

we all know that if you are not attacking anyone and no one is attacking you automatically you leave the combat mode and you can eat, mount and in the case of the rogue use his invisibility mode after 5 seconds but this does not happen like that.
