### ISSUE TITLE
pets are very healthy

### ISSUE THREAD

**Issue by Soulprincesss** [Unlimited-WoW/BugTracker#110]
The pets of both the warlock and the hunter have a lot of life, even greater than that of the same owner.
This should not be the case, normally on low or high servers the pets have half the life of the hunter's duel... if a hunter has 700 million life the pet should have a maximum of 350 to 450 million. but they get to have 900 million...

**Comment by GladiatorUW** [comment]
Currently asking players for #suggestions about this report on discord.

**Comment by GladiatorUW** [comment]
![image](https://user-images.githubusercontent.com/31390127/166153119-2d03e6be-d7a4-49e7-a464-c71e13d254cd.png)
nerfed the maximum HP buff
