### ISSUE TITLE
Login Issues

### ISSUE THREAD

**Issue by Tazzdinka** [Unlimited-WoW/BugTracker#113]
Failed to apply Patch

When I enter my info at the title screen it lets me enter but says downloading 0% then tells me Patch Required and boots me back to login
**Current Behavior:**
Keeps telling Patch required no matter what I do

**Expected Behavior:**

To be able to finish the download and go to character creation.

**Source:**
I tried looking everywhere to fix this problem but found nothing except that another person had an issue with this in December 2021 but there was no resolution.

**Steps to reproduce the problem:**

1. Login with username/password
2. Download 0%
3. Patch Required 
![Screenshot (7)](https://user-images.githubusercontent.com/103562443/163127423-6493f32f-4a0f-4469-9bb3-a6b9ccbb7c7c.png)

**Comment by GladiatorUW** [comment]
Once you did download World of Warcraft 3.3.5a, open the directory & you can start playing by running wow.exe
Remember to login with your username and not your e-mail adress.
