### ISSUE TITLE
Devouring-plague

### ISSUE THREAD

**Issue by lanstus192** [Unlimited-WoW/BugTracker#115]
Class: Priest
Spell: Devouring-plague
Report reason: 500-600 Shadow damage per tick. 

If i use this spell on char/mobs, it deals 500-600 damage only. 
If i use this spell on Dummies, it deals 1 damage only. 
No different with the Talent (Improved Devouring-plague)

I tested every Rank, but it deals not more than 600 damage per tick.

**Comment by GladiatorUW** [comment]
The spell works fine, it does 1 dmg only against dummies but not to creatures/players
