### ISSUE TITLE
Warrior - Shield Block doesn't work at all

### ISSUE THREAD

**Issue by dacoshild** [Unlimited-WoW/BugTracker#127]
**Description:**

Warrior ability Shield block is not working at all.

**Current behaviour:**

If you use Shield Block for warrior, the buff goes up, but the chance to block stays the same. So It's basically not working at all.

**Expected behaviour:**

It should increase the block chance and block value by 100%.

**Source:**

(https://www.wowhead.com/wotlk/spell=2565/shield-block)

**Steps to reproduce the problem:**

I just pulled whatever mob and cast it. It was blocking like each 10th attack, which correspond to tooltip in my character screen which is always 10%. I tried different shields, mobs and even weapons. It just doesn't work.

**Comment by GladiatorUW** [comment]
This is because the max block cap % is set to 10%
