### ISSUE TITLE
Starter Guide for New Players

### ISSUE THREAD

**Issue by Takenyourbacon** [Unlimited-WoW/BugTracker#129]
This information is posted because the amount of questions regarding locations of certain NPCs or "Quest Givers" etc. 
These are the locations of some of the starter npcs you'll be using regularly . You can also use the teleporter NPC to get around. The Hearthstone and "Mini- Teleporter" are also forms of transportation. New players can bypass leveling their weapon skills from 1-450 by typing .Maxskill. Speak with the "Class Trainer" NPC to learn all of your classes spells and abilities. Don't forget to buy glyphs via the glyph vendor near the Gem/Enchanting Vendors in the mall. If you'd like to know F.A.Qs about the server the NPC listed in the screenshot can give you details of the servers history and information. Patch 7&8 are now included in the download from the site https://unlimited-wow.com/page/connect  . To create an account with Unlimited-Wow You can use this hyperlink  https://unlimited-wow.com/register
Voting for the server not only helps promote the server to increase player base but it also rewards you with 5 VP [Vote Points] daily, which can be exchanged for certain material and items.

If you are having issues with using weapons first confirm that you've trained all of your weapons available from the "Weapon Trainer" NPC in the Servers Mall.
Once you've done that, if you still cannot use any of the melee abilities for your class while having a weapon equip. You are probably missing the patch 7&8. You can find those on this discord, or the site. You place the patches in your DATA Folder inside your wow folder. Once you do that, delete the cache folder inside your wow folder, and restart your game, if the issue persists, you've done something wrong, try to reinstall the patches. If more information is required feel free to privately message me, ingame or on discord.

Tier Information:
Progression from Tier 1 to Tier 13 can be a bit challenging for a new player who has never done any Fun Server style content. 
Prior to starting tier 1, head over to "Teleporter->Custom Zone->Element Zone" Once there you can choose your weapons of choice that you'd like to begin leveling up. For example, for a shaman you can buy a Axe & Dagger from the Elemental NPC @Element Zone for the materials that can be found outside the entry point of the Element Zone. Once you've farmed the material for the first weapon, there are 3 more upgrades that can be farmed inside the Element Zone. You should upgrade your weapons until they reach the level known as Metal. Metal weapons can be purchased for 400 Metal Element, & The Previous Weapon. So essentially you'll turn in your old weapon for a upgrade each time you progress through the Elements. Once you've reached maximum weapon level known as Metal Element Weapons you can begin working on your gear!
Tier 1. Ragefire Chasm is Tier 1. There is a quest giver on the outside of the instance. You can speak to them and get every quest for mainset from helmet to boots. Most of the items will require you to get "Armor Parts" which can be found inside the Tier 1 Instance. That being said each instance usually contains the materials required for the next upgrade weather its tier 1 or tier 20. Although some quests require outside items such as Silver & Gold which can be found at the Pig Instance via teleporter under Custom Zones.
If any more information is needed regarding tiers and the items required locations of gathering etc, please lmk.

World bosses; World bosses are usually a team based effort. Such bosses as Poseidus of Naias or Lord Kapre can somewhat be soloable depending on your current progression. World bosses drop materials up until you reach World boss Emeriss. Who drops tier 20 mainset randomly. Killing other bosses such as Doom Lord Kazzak, Omen & Azuregos will drop tier 21, tier 22, and tier 23. In that order. With each boss increasing in gear, as does the level of gear/skill required to slay said boss. World bosses can be found by going to the teleporter -> world bosses.

Transmog Content. Currently there are 4 different zones in which you can begin working on your transmog gear!
Transmog Mall-> Which gives you free items based on previous expansions tier sets, [Which is all strictly visual purposes]
Supremus-> Supremus drops Amor from the trash mobs and the boss, higher gear is required to kill the trash mobs and the boss. I suggest not entering until atleast tier 18 every slot.
Obsidan Sanctum-> OS is a weapon dropping zone/boss you can farm nice transmog weapons. Requires atleast t15 I'd say.
Cata Transmog -> This zone is brand new and it's made with the intention of players with endgame gear like t23+ to farm it! It has exclusive new cata transmog items!

Keys -> Keys are required to enter most instances/raids to get a key quest speak to the Key Quest NPC in the mall for the quest pertaining to your current teir. You can find the material for the Tier Key Quest in the previous dungeon on the Teleporter->Instances List.

**Comment by Takenyourbacon** [comment]
For more information PM me on discord @Nightmare#9232 or ingame by the name of Totem or Nightmare.

**Comment by GladiatorUW** [comment]
Thanks for the guide but this section is only for bugs
