### ISSUE TITLE
Warlock donor set issue

### ISSUE THREAD

**Issue by django-Oskie** [Unlimited-WoW/BugTracker#13]
**Description:**

I have 4 piece of the donor warlock set (belt, boots, gloves and shoulders) . But the 4 piece bonus is not activated. I have similar set for paladin, but for it it is activated

**Current behaviour:**

I have 4 piece of the donor warlock set (belt, boots, gloves and shoulders) . But the 4 piece bonus is not activated. I have similar set for paladin, but for it it is activated

**Expected behaviour:**

4 piece bonus should be activated. Plus the 4 piece bonus is minuscle, only 88 sp bonus . Similar to the 2 piece bonus, only 29 sp bonus. That needs to be buffed. 

**Steps to reproduce the problem:**

1. Get 4 pieces of the warlock donor set  (belt, boots, gloves and shoulders)
2. go to character screen and hover over the set items
3. 4 piece bonus is not activated

**Comment by izjgod** [comment]
its activatd, only transmog makes it look like it isnt activated,
