### ISSUE TITLE
Problem With The Cata Dagger (The Sleeper)

### ISSUE THREAD

**Issue by Iappear** [Unlimited-WoW/BugTracker#131]
Cata Dagger Main Hand Not Being Able To Mog

I farmed the Cata dagger which is the main hand one, and now I can't seem to be able to mog it onto any wep.

Current behaviour: Not working on any dagger or any wep in general.

Tell us what happens.

Expected behaviour: Should be able to mog this dagger onto my donor dagger.

Proof, e.g wowwiki link.

![Bug](https://user-images.githubusercontent.com/114156294/191740632-f1a10cd5-e7f2-4938-8fcc-00cc825986a6.PNG)

**Comment by GladiatorUW** [comment]
Will be applied next restart
