### ISSUE TITLE
Normal Mobs T19 DMG Abnormal

### ISSUE THREAD

**Issue by lukav7** [Unlimited-WoW/BugTracker#132]
there normal mobs name Crystalcore Devastator at T19
who give abnormal dmg like this
![WoWScrnShot_092222_215641](https://user-images.githubusercontent.com/113808363/191781808-6209ee5b-8fab-4944-bbe7-4cd7569de467.jpg)

is this normal?
after couple of killing it with spam,sometime the DMG peak can be 170M

**Comment by GladiatorUW** [comment]
We are still working on the rework T19-T23, mentioned last week @ discord  #changelog. Will be pushed today.
