### ISSUE TITLE
[Transmog] Golden Gladiator's Fist  - 270041

### ISSUE THREAD

**Issue by fssn-dev** [Unlimited-WoW/BugTracker#133]
**Description:**

Golden Gladiator's Fist cannot be transmogged

**Current behaviour:**

Golden Gladiator's Fist have skins listed in the transmog NPC. Applying a set saved beforehand will ignore said weapons and work on the rest.

**Expected behaviour:**

Golden Gladiator's Fist should show all available fists in the character inventory under the transmog NPC menu and it should change when a saved set is applied

**Source:**

[https://unlimited-wow.com/item/1/270041](https://unlimited-wow.com/item/1/270041)

**Comment by GladiatorUW** [comment]
Golden Gladiator's Fist transmog works fine, tested with 2hands, one handed weapons, also transmogging into Golden Gladiator's Fist works.
