### ISSUE TITLE
DK Talent Unholy Blight in Intances 

### ISSUE THREAD

**Issue by Flopper544** [Unlimited-WoW/BugTracker#136]
**Description:**

Going into any of the T intances using death coil on a mob it dosnt apply unholy blight

**Current behaviour:**

Using death coil dose not apply Unholy Blight in an intance  

**Expected behaviour:**

use death coil applys unholy blight dot to mob

**Source:**

Proof, e.g wowwiki link.

**Steps to reproduce the problem:**

1. Go to an intacne start attacking a mob to generate rune essene   
2. Use death coil
3.  watch the dot no be aplied to the mob you are attacking

**Comment by GladiatorUW** [comment]
Not a bug, its disabled in some areas
