### ISSUE TITLE
Frost Strike bug (1 shots ppl)

### ISSUE THREAD

**Issue by Nemiifest** [Unlimited-WoW/BugTracker#144]
**Description:**

Description of the problem or issue here.
Frost strike rank 1 is buggy as hell and hits ppl up to 400-600m, literally 1 shotting people and needs to be disabled, 

**Current behaviour:**
Frost Strike rank 1 hits like 10 times harder than the max rank (6)

Tell us what happens.
Crits over 400-600m and 1 shots ppl
**Expected behaviour:**
Not do more dmg than frost strike rank 6 and clearly not 1 shot ppl by causing 400-600m dmg
Tell us what should happen instead.
Disable frost strike r1 = problem solved.
**Source:**

Proof, e.g wowwiki link.

**Steps to reproduce the problem:**

1. Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.  
2. Step 2
3. Step 3

**Comment by GladiatorUW** [comment]
Can't reproduce this bug but disabled low ranks anyway.
