### ISSUE TITLE
Hit rating on silver items

### ISSUE THREAD

**Issue by Misses-H** [Unlimited-WoW/BugTracker#146]
**Description:**
There are a few silver level off set items that have 14000 hit rating.

**Current behaviour:**

You exceed the hit cap and then the rating defaults to 0. Then you miss a lot.

**Expected behaviour:**

Hit rating should be adjusted to not ever go over the cap. I personally do not know the cap. I think maybe removing two zeros would be suitable. 

**Source:**

Proof, e.g wowwiki link.

**Steps to reproduce the problem:**

1. Step 1 Silver Tabard  
2. Step 2 Silver Trinket
![WoWScrnShot_120522_133330](https://user-images.githubusercontent.com/119894567/205737710-4dea28a8-00b5-499f-bcba-f07c466dc78d.jpg)
![WoWScrnShot_120522_133338](https://user-images.githubusercontent.com/119894567/205737713-86477333-9cb3-4e5b-8724-496e862e1afc.jpg)

3. Step 3

**Comment by GladiatorUW** [comment]
Will be auto applied after next restart, thanks for reporting
