### ISSUE TITLE
T1 T3 T14 T16 thrown

### ISSUE THREAD

**Issue by Charlieshiv** [Unlimited-WoW/BugTracker#15]
**Description:** T1 T3 T14 T16 thrown for rogues are made as "Ranged" instead of Thrown so we can't use it as rogues

Description of the problem or issue here.

**Current behaviour:**

Tell us what happens.

**Expected behaviour:**

Tell us what should happen instead.

**Steps to reproduce the problem:**

1. Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.  
2. Step 2
3. Step 3

**Comment by GladiatorUW** [comment]
This was probably fixed a while ago, can't reproduce
