### ISSUE TITLE
Can't transmog  [Gladiator's Salvation] mace

### ISSUE THREAD

**Issue by Rpgodx** [Unlimited-WoW/BugTracker#150]
Description:
Can't transmog  [Gladiator's Salvation] mace

Description of the problem or issue here.

Current behaviour:
Doesnt show up as transmog, I tried deleting cache, updating transmog menu, relog, have both patches.

Tell us what happens.
It just doesn't show up as transmog

Expected behaviour:
Could have been transmogable

Tell us what should happen instead.

Source:

Proof, e.g wowwiki link.
https://www.wowhead.com/wotlk/item=32451/gladiators-salvation
https://wowwiki-archive.fandom.com/wiki/Gladiator%27s_Salvation

**Comment by GladiatorUW** [comment]
Its a main hand mace, you'll need a main hand item to make it transmogable.
