### ISSUE TITLE
Abolish Disease bugged

### ISSUE THREAD

**Issue by Nemiifest** [Unlimited-WoW/BugTracker#153]
**Description:**

Description of the problem or issue here.
Abolish disease removes poisons when it should only remove diseases

**Current behaviour:**
removes more debuffs than what it should

Tell us what happens.
Abolish dispells poisons? xd
**Expected behaviour:**
Should only dispel Diseases and not Poisons.
Tell us what should happen instead.
what i said above ^
**Source:**

Proof, e.g wowwiki link.

**Steps to reproduce the problem:**

1. Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.  
2. Step 2 
3. Step 3

**Comment by Rpgodx** [comment]
Its not bugged, priest talent [Body and Soul] removes poisons also.
[Body and Soul] - When you cast Power Word: Shield, you increase the target's movement speed by 60% for 4 sec, **and you have a 100% chance when you cast Abolish Disease on yourself to also cleanse 1 poison effect in addition to diseases.**
https://www.wowhead.com/wotlk/spell=64129/body-and-soul
