### ISSUE TITLE
Donor Sword missing dmg

### ISSUE THREAD

**Issue by sebogjokke** [Unlimited-WoW/BugTracker#156]
Hi. I recently bought the donor weapon " [Donor Sword]" for tmog, and I noticed that it doesnt work as intended. The dmg you get from the weapon is lower than from  [Donor Sword Thunderfury] which is supposed to be the exact same. Can you please look into this and fix the dmg so it matches the thunderfury?
Seems like the coding on the weapon isnt working as intended
7 mill +- less dmg
same stats and everything, so idk
**Description:**
"Donor Sword" has less dmg than other donor weapons, when its supposed to be equal. Around 7-8 mill in total reduction when I use this instead of fexample thunderfury.

Description of the problem or issue here.
Dmg is not as intended
**Current behaviour:**
Less dmg than other one hand donor weps
Tell us what happens.

**Expected behaviour:**
Equal dmg to the other one handed weapons
Tell us what should happen instead.

**Source:**

Proof, e.g wowwiki link.

**Steps to reproduce the problem:**

1. Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.  
2. Step 2
3. Step 3

**Comment by GladiatorUW** [comment]
Tested with starter gear warrior and 1x of the reported items. They do the same around 13m white melee

Donor Sword (Thunderfury)
![image](https://user-images.githubusercontent.com/31390127/210086687-22946aec-ee6e-4afb-89ef-ac8a3b282e7a.png)

Donor Sword
![image](https://user-images.githubusercontent.com/31390127/210086748-ace9795d-21b5-4015-8402-672ee54e3fad.png)
