### ISSUE TITLE
Warrior Donor 4-set piece not working as intended

### ISSUE THREAD

**Issue by immeasurably91** [Unlimited-WoW/BugTracker#165]
**Description:**

When i activate my Bloodrage ability

**Current behaviour:**

Nothing

**Expected behaviour:**

A buff that puts an absorbing shield based on 20% of my hp

**Source:**

Just look at the screenshot

![2023-01-20 11_04_56-World of Warcraft](https://user-images.githubusercontent.com/47146788/213669981-7ae30e8c-6db6-4f0b-b9ea-bf548dfc8f21.png)

**Comment by Loneberzerker** [comment]
+1

**Comment by GladiatorUW** [comment]
Enabled again.
