### ISSUE TITLE
Glyph of stoneclaw totem

### ISSUE THREAD

**Issue by immeasurably91** [Unlimited-WoW/BugTracker#177]
Hello,

I noticed Glyph of Stoneclaw totem isn't working ( has worked before ).
It should absorb damage from the player once the totem is dropped ( i believe it was around 60m before? ).

I noticed this after T25 launched and wanted to test my shaman with the new gear.
![2023-04-28 00_58_59-World of Warcraft](https://user-images.githubusercontent.com/47146788/235008611-86a4f3f8-b583-4739-aa82-eeeab2f6c53e.png)
![2023-04-28 00_59_15-World of Warcraft](https://user-images.githubusercontent.com/47146788/235008618-d78b34c1-4b82-4d59-8a4d-06ac0b438891.png)
![2023-04-28 01_01_43-World of Warcraft](https://user-images.githubusercontent.com/47146788/235008733-dcf5e7b0-a0f1-4f67-9fad-46bdaa2cde31.png)
![2023-04-28 01_01_47-World of Warcraft](https://user-images.githubusercontent.com/47146788/235008737-c0849f25-3192-439d-a762-33cc0bd0ded3.png)

As you can see i am using the glyph and have my totem down, but there is no absorb nothing.

**Comment by GladiatorUW** [comment]
You are wrong, this totem was never absorbing damage before on UW. You must be talking about another server.
