### ISSUE TITLE
Flying without a mount

### ISSUE THREAD

**Issue by Crimer90** [Unlimited-WoW/BugTracker#18]
**Description:**

When i am on a Flying Mount (Onyx Netherwing Drake) and fly inside the T18 Instance, than can i fly without a mount. when i go outside the instance, it works anymore.

**Current behaviour:**

Tell us what happens.

**Expected behaviour:**

I should not be able to fly.

**Steps to reproduce the problem:**

1. Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.  
2. Step 2
3. Step 3

**Comment by GladiatorUW** [comment]
Please reopen this in case it still happens
