### ISSUE TITLE
Enhancement Shaman's Lava Lash does not work when having 2 - two handed axes

### ISSUE THREAD

**Issue by luismeramosr** [Unlimited-WoW/BugTracker#181]
**Description:**
I got the scroll of Titan's Grip then got 2 - two handed axes and i cant use the Lava Lash ability. I want to specify that i already have all the patches installed. I checked 2 times.
Description of the problem or issue here.
It says "Must have a melee weapon equiped". It does not allow to use the spell, when i swap with oter one handed weapon it works.
**Current behaviour:**
Lava Lash does not work.
Tell us what happens.
When trying to use Lava Lash it just does not work displaying "Must have a melee weapon equipped", but if i use a 1 hand weapon in the offhand it works.
**Expected behaviour:**
It should work regardless of the offhand weapon being 1 handed or 2 handed, because both are melee weapons.
Tell us what should happen instead.
Lava Lash should be able to be used with one handed and two handed weapons.
**Source:**
Two - handed axe
![image](https://github.com/Unlimited-WoW/BugTracker/assets/41213455/bf5cd50c-2c42-4e18-a982-0b7842873333)

One - handed fist weapon
![image](https://github.com/Unlimited-WoW/BugTracker/assets/41213455/e40deba6-5d06-4396-bead-054496dab3ea)

Proof, e.g wowwiki link.

**Steps to reproduce the problem:**

1. Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.  
2. Step 2
3. Step 3

**Comment by GladiatorUW** [comment]
This spell can only be used with a one-handed weapon
