### ISSUE TITLE
Rogue talent causing combat bugs

### ISSUE THREAD

**Issue by immeasurably91** [Unlimited-WoW/BugTracker#184]
Can you disable the following talent?
This talent causes rogues to be in constant combat in bg's , making them unable to stealth because whenever someone heals or attacks they get the rogue in combat with this.

This isnt supposed to cause combat.

![2023-05-26 21_41_36-World of Warcraft](https://github.com/Unlimited-WoW/BugTracker/assets/47146788/f490bfee-ad2b-4627-9032-210a00d6d625)

**Comment by GladiatorUW** [comment]
Have you tested it because I cannot reproduce this?

**Comment by immeasurably91** [comment]
Hey, yeah we've tested it with multiple rogues.

It's being caused in party /raid groups.
Whenever someone enters combat in a bg you get the combopoint but that's causing you to get infinite combat untill you die as a rogue.
