### ISSUE TITLE
game is crashing after press c

### ISSUE THREAD

**Issue by Unhygenix** [Unlimited-WoW/BugTracker#186]
**Description:**
when i am press c the game will crash
Description of the problem or issue here.

**Current behaviour:**

Tell us what happens.

**Expected behaviour:**

Tell us what should happen instead.

**Source:**

Proof, e.g wowwiki link.

**Steps to reproduce the problem:**

1. Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.  
2. Step 2
3. Step 3

**Comment by GladiatorUW** [comment]
You clearly didn't read the connection guide: https://unlimited-wow.com/downloads/DruidFix.rar Install this addon
