### ISSUE TITLE
Donor hunter gear Does not give the stats it say.

### ISSUE THREAD

**Issue by rngdudu** [Unlimited-WoW/BugTracker#190]
**Description:**
Donor Hunter shoulders are broken
Description of the problem or issue here.
I have found a bug where I do more dmg with T25 shoulders than Donor shoulders.
**Current behaviour:**
I tested in duel vs the same guy, With donor my Expolsive shot hit for 56m But with T25 my Explosive shot hit for 62m
Tell us what happens.

**Expected behaviour:**
Donor shoulders have more stats even without all the "equip" bonuses but still give less dmg? im guessing they are not giving the stats they say they give.
Tell us what should happen instead.
Fix so the donor shoulders makes you do more dmg, because one of the "equip" Effects is 6% more crit dmg witch then looks weird that I do less with donor gear.
**Source:**
Me and a fellow hunter who found the bug.
Proof, e.g wowwiki link.

**Steps to reproduce the problem:**

1. Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.  
2. Step 2
3. Step 3

**Comment by GladiatorUW** [comment]
Tested and donor shoulders is clearly doing more damage with the reported spell Explosive Shot (tested with rank 4)
