### ISSUE TITLE
Item in my character is causing a system crash

### ISSUE THREAD

**Issue by Delvin1618** [Unlimited-WoW/BugTracker#192]
**Description:** 

When I log in to my character Lorgoran, the WOW system immediately crashes. Is it possible to remove all my armor so I can log in to my character to see if that fixes the problem? Take a look at the screenshot. 
Description of the problem or issue here.
![Screen Shot 2023-08-15 at 2 15 41 PM](https://github.com/Unlimited-WoW/BugTracker/assets/85963757/35b6fdf4-3a26-4932-ace9-d437958af0e9)

**Current behaviour:**

Tell us what happens.

**Expected behaviour:**

Tell us what should happen instead.

**Source:**

Proof, e.g wowwiki link.

**Steps to reproduce the problem:**

1. Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.  
2. Step 2
3. Step 3

**Comment by GladiatorUW** [comment]
Make sure you have patch 7 & 8 installed correctly. If it still happens post the crashlog here.
