### ISSUE TITLE
Gigantic Feast

### ISSUE THREAD

**Issue by johhny455** [Unlimited-WoW/BugTracker#195]
**Description:**
Gigantic Feast Cooking 425
Description of the problem or issue here.

**Current behaviour:**

Tell us what happens.
When you get to 20 seconds left to yeah it says the spell is not available for you
**Expected behaviour:**
It should increase your size.
Tell us what should happen instead.

**Source:**

Proof, e.g wowwiki link.
https://wowwiki-archive.fandom.com/wiki/Gigantic_Feast
**Steps to reproduce the problem:**

1. Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.  
2. Step 2
3. Step 3
![gigantic](https://github.com/Unlimited-WoW/BugTracker/assets/59595930/0fbbedef-bb9a-40d0-889f-67db757c8bf4)

**Comment by GladiatorUW** [comment]
Thats because the spell is disabled.
