### ISSUE TITLE
Rogue donor item not fully functional

### ISSUE THREAD

**Issue by Lexq101** [Unlimited-WoW/BugTracker#196]
**Description:** The 6% dodge bonus from the rogue donor legs is not being applied.

Description of the problem or issue here.

**Current behaviour:**

Tell us what happens.

**Expected behaviour:** Dodge % chance should increase

Tell us what should happen instead.

**Source:** In-game

Proof, e.g wowwiki link.

**Steps to reproduce the problem:**  Equip the item in-game.

![image](https://github.com/Unlimited-WoW/BugTracker/assets/147171652/207bf99f-8a57-4279-adc5-0cf7f11f8a1a)
![image](https://github.com/Unlimited-WoW/BugTracker/assets/147171652/e3e453ba-c6a6-464d-8e8f-9c63442ee839)

**Comment by GladiatorUW** [comment]
It is capped at 20%
