### ISSUE TITLE
Evasion not providing the correct buff

### ISSUE THREAD

**Issue by Lexq101** [Unlimited-WoW/BugTracker#197]
**Description:**

 The buff given when the spell is pressed is incorrect.

**Current behaviour:**

 Instead of Evasion, which is the correct buff the character is given 20 stacks of Retaliation which is a warrior spell.

**Expected behaviour:** 

The buff given should be Evasion and also it should provide 50% dodge chance as well as 25% reduced chance for ranged attacks to hit. 
Currently in game the tooltip reads 25% dodge chance and 5% reduced chance for ranged attacks to hit.

**Source:**

 https://www.wowhead.com/wotlk/spell=5277/evasion#comments
https://www.wowhead.com/wotlk/spell=20230/retaliation

Proof, e.g wowwiki link.

**Steps to reproduce the problem:** 

Use buff on a rogue character

![image](https://github.com/Unlimited-WoW/BugTracker/assets/147171652/680ec597-845e-4eaa-9bab-b489ace603b7)
![image](https://github.com/Unlimited-WoW/BugTracker/assets/147171652/40bcdb6a-1cb0-42a0-a661-e87eff93b5b7)

**Comment by GladiatorUW** [comment]
This was changed years ago since dodge was capped at 20%
