### ISSUE TITLE
Bug Hunter Pet

### ISSUE THREAD

**Issue by redforce112** [Unlimited-WoW/BugTracker#198]
There is a problem with Kindred Spirits, you have to have 20% but after a logout you lose 20% and it becomes 12%, I tried to reset the skill and as soon as I log out the bug returns again
https://gyazo.com/2440e039be69e313a6593b703292e81d
https://gyazo.com/065dbdfc17b28035ac860f16f8cfc289

**Comment by GladiatorUW** [comment]
It remains 20% for me after a relog. Tried several times.
