### ISSUE TITLE
Kill Jaeden bugg

### ISSUE THREAD

**Issue by boykevink** [Unlimited-WoW/BugTracker#2]
**whenever i kill kill jaeden i cant loot him every time. this happens 3 out of 8 times for me now:**

Description of the problem or issue here.

**when i kill him i can not look him everytime:**

Tell us what happens.

**i expect to be able to loot the final boss of tier 13 because i killed him:**

Tell us what should happen instead.

**i think this happens when a talent of a players gets the killing blow on the boss but i cant prove that is the case:**

1. Step 1 i believe this alos effect golden phoenix's in golden phoenix zone.  
2. Step 2
3. Step 3

**Comment by izjgod** [comment]
this issuse, is very core probleme but on a retail in 3.3.5a this wasnt a real bug, but on most blisslike servers this issuse occur, my tips as an experienced pver, avoid an ability talent aura effect enchant that hits an extra dmg close to end of the boss,

**Comment by boykevink** [comment]
i am a rogue.not sure how to do that...

**Comment by izjgod** [comment]
as a rogue, ur Dodge talent, /thorn from buffer, just finish him with bleeds,

**Comment by CreedUW** [comment]
Tested issue, could not reproduce.
