### ISSUE TITLE
Bug - Bronze Gladiator's Doomsday II

### ISSUE THREAD

**Issue by LewisWelch94** [Unlimited-WoW/BugTracker#207]
**Description:**

Incorrect weapon requirement, having it as it is would make the base weapon obsolete 

**Current behaviour:**

Both base & level 2 Bronze Gladiator's Doomsday require:

1 x Metal Element Doomsday
250 x Shadowfang Keep Token
250 x Super Weapon Token
250 x Lost Amethyst
250x 50,000 Demon Heads Coupon

**Expected behaviour:**

Base Weapon:

1 x Metal Element Doomsday
250 x Shadowfang Keep Token
250 x Super Weapon Token
250 x Lost Amethyst
250x 50,000 Demon Heads Coupon

Level 2:

1 x Bronze Gladiator's Doomsday
250 x Shadowfang Keep Token
250 x Super Weapon Token
250 x Lost Amethyst
250x 50,000 Demon Heads Coupon

Note: perhaps make the other materials cost more aswell? not a bug, just incosistent.

**Source:**

![image](https://github.com/Unlimited-WoW/BugTracker/assets/48370571/37ec2227-d65a-440e-b848-8e06e86cb021)

**Steps to reproduce the problem:**

1. Step 1: Checking both base level & level 2 quest requirements.

**Comment by apeeso12** [comment]
both quests lead to the same rewards and require the same exact items to get said rewards. you obtain the metal element first then trade it in for bronze gladiator 1 or 2 gives the same items

**Comment by LewisWelch94** [comment]
> both quests lead to the same rewards and require the same exact items to get said rewards. you obtain the metal element first then trade it in for bronze gladiator 1 or 2 gives the same items

Yep been playing longer, and I see this is how the server does the quests for off-hand weapons of the same type.
I assume II would be an upgrade, closing issue
