### ISSUE TITLE
DB Chili

### ISSUE THREAD

**Issue by immeasurably91** [Unlimited-WoW/BugTracker#209]
Dragonbreath chili is scaling with Spellpower, resulting in increased dmg on certain classes ( rogue for example )
![image](https://github.com/Unlimited-WoW/BugTracker/assets/47146788/bb01307b-de63-463d-ab6d-7e10aeaf048e)

**Comment by GladiatorUW** [comment]
https://wowpedia.fandom.com/wiki/Dragonbreath_Chili
