### ISSUE TITLE
Fail appling patch

### ISSUE THREAD

**Issue by LieWicho** [Unlimited-WoW/BugTracker#21]
**Description:**

Cant apply patch

**Current behaviour:**

When you enter it gets cold and appear a message saying "downloading update" after clicking ok or cancel you get back to the menu

Tell us what should happen instead.

Enter to the game

1. Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.  
2. Step 2
3. Step 3

**Comment by GladiatorUW** [comment]
You have to start the game by wow.exe not from the launcher.
