### ISSUE TITLE
HIT RATING

### ISSUE THREAD

**Issue by nightbaneftw** [Unlimited-WoW/BugTracker#22]
**Description:**

Hit rating is bugged, if the person has full set of attack power offsets(rings, neck, fingers, trinkets) the hit rating goes to 0 https://i.imgur.com/yemkFAO.jpg and the person missed 20% of time

**Current behaviour:**

Hit rating is bugged, if the person has full set of attack power offsets(rings, neck, fingers, trinkets) the hit rating goes to 0 https://i.imgur.com/yemkFAO.jpg and the person missed 20% of time

**Expected behaviour:**

The hit rating needs to continue being above 100% and to people to never miss

**Steps to reproduce the problem:**

1. Step 1 equip all of the offsets  
2. Step 2 0 hit rating
3. Step 3 remove 1 offset
4. step 4 100% + hit rating

**Comment by CreedUW** [comment]
Fixed on most items
