### ISSUE TITLE
Problem with power information

### ISSUE THREAD

**Issue by babylyonleonn** [Unlimited-WoW/BugTracker#220]
**Description:**

Description of the problem or issue here.
when I want to know the information about each power or each attack, to accommodate it, but it doesn't give me information

**Current behaviour:**

Tell us what happens.

In the power book, even past powers appear to me, which does not remove and not having the information sends me one that is of lower rank.

**Expected behaviour:**

Tell us what should happen instead.

Clicking on the icon to not show past powers, which will allow me to choose only the current power, additionally having the information that each power does will be very helpful.

**Source:**

Proof, e.g wowwiki link.

I don't know how to do this but I leave a link to the images.

https://ibb.co/KwVPsGy 

https://ibb.co/fMLnthf
 
https://ibb.co/fFwKyyG  

https://ibb.co/KwVPsGy 

**Steps to reproduce the problem:**

1. Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.  
2. Step 2
3. Step 3
![Snap 2024-01-27 at 15 17 17 - copia](https://github.com/Unlimited-WoW/BugTracker/assets/157922544/151d208d-8d3f-4709-8665-2b8c595b171b)
![Snap 2024-01-27 at 15 17 17](https://github.com/Unlimited-WoW/BugTracker/assets/157922544/2caf14b1-a9b0-4622-a413-50875aff8ae1)
![Snap 2024-01-27 at 15 16 36](https://github.com/Unlimited-WoW/BugTracker/assets/157922544/fea64ad4-ac33-4db4-bd22-76c7d8b4f425)
![Snap 2024-01-27 at 15 16 05](https://github.com/Unlimited-WoW/BugTracker/assets/157922544/27dbc322-be1b-4577-a0f2-b462e7b80781)

**Comment by GladiatorUW** [comment]
This is related to your settings, reset your UI
