### ISSUE TITLE
Crit rating

### ISSUE THREAD

**Issue by nightbaneftw** [Unlimited-WoW/BugTracker#23]
**Description:**

For some reason the crit is 80% and people miss sometimes

**Current behaviour:**

For some reason the crit is 80% and people miss sometimes

**Expected behaviour:**

Crit to be above 100%, so people crit all the time

**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Comment by CreedUW** [comment]
Crit will no longer overcap
