### ISSUE TITLE
DKs have aditional spells

### ISSUE THREAD

**Issue by nightbaneftw** [Unlimited-WoW/BugTracker#24]
**Description:**

DKs currently have aditional pestilence and stragulate https://i.imgur.com/2KEOiHO.jpg

**Current behaviour:**

DKs currently have aditional pestilence and stragulate https://i.imgur.com/2KEOiHO.jpg

**Expected behaviour:**

Dks are supposed to have just 1 strangulate na 1 pestilence

**Steps to reproduce the problem:**

1. Step 1 open your spellbook
2. Step 2
3. Step 3

**Comment by CreedUW** [comment]
They are disabled
