### ISSUE TITLE
Unhittable/Unkillable Loken

### ISSUE THREAD

**Issue by mattyhead** [Unlimited-WoW/BugTracker#242]
**Description:**

In Halls of LIghtning, Loken is unkillable.

**Current behaviour:**

Loken fades and evades when attacked.

**Expected behaviour:**

He should not fade and not evade when attacked.

**Source:**

N/A

**Steps to reproduce the problem:**

1. Step 1 Walk up to Loken 
2. Step 2 Try to hit him
3. Step 3 Watch him fade and evade

**Comment by mattyhead** [comment]
Update.  In my test run, I had a better equipped character facing Loken and two lowbies parked at the entrance.  Doing a solo clear, the fade/reset did *not* occur.  I will fully run again with the alts in tow and report on the results.

**Comment by mattyhead** [comment]
Final update:  New test run with alts.  Even if the alts are in Loken's aggro range, he performs the fade/evade mechanic.  Bug.

**Comment by GladiatorUW** [comment]
You have to kill all other bosses to unlock Loken. Tested and works fine ..

**Comment by soluicius** [comment]
> You have to kill all other bosses to unlock Loken. Tested and works fine ..

I killed them all and Loken is still unhittable/unkillable...
<img width="1522" alt="Screenshot at Nov 11 13-12-39" src="https://github.com/user-attachments/assets/3aef1ef6-6d47-482a-a8c8-99c8493e953a">
