### ISSUE TITLE
"Error creating character" can't create a female Draenei character

### ISSUE THREAD

**Issue by MoonCheetah** [Unlimited-WoW/BugTracker#27]
**Description:**

Every time I try to create a female Draenei character on the WOTLK server I get the "error creating character" message. It doesn't seem to matter which class or customization I choose. I tried a variety of different names, as well. All other races seem to work just fine.

**Current behaviour:**

I can't create a female Draenei character due to the error described above.

**Expected behaviour:**

It should allow me to create a character, obviously. 

**Steps to reproduce the problem:**

1. Step - There are no steps so I am just going to provide you with a screenshot of the problem instead.
![WoWScrnShot_090819_234651](https://user-images.githubusercontent.com/55065735/64494971-03aa5c80-d294-11e9-8809-77bd36a16976.jpg)

**Comment by Falseformat** [comment]
I'm still having this issue, is there any fix for it? Draenei are my favorite :(

**Comment by GladiatorUW** [comment]
Please try different features such as face, hair.
