### ISSUE TITLE
Game disconnects when linking Bronze Gladiator's Totem

### ISSUE THREAD

**Issue by thereporter42** [Unlimited-WoW/BugTracker#28]
**Description:**

When you try and link the the item 
"Bronze Gladiator's Totem" to a channel it logs you out of the 
game I tried linking it to a guild channel as well as to the world 
channel and as well in a party channel and all of them crashed
when I tried to link the item to the channel.

This was occurring on September 14 2019 at about 
12:00 PM MST (GMT-0700) 

Item can be seen here: 
https://ibb.co/5949tNL

![Bronze Gladiator's Totem Unlimted Wow Sept 14 2019](https://user-images.githubusercontent.com/38896397/64912122-ec320000-d6e7-11e9-8b61-aa7bf7d9deee.jpg)

**Current behaviour:**

The game will just disconnect you and it will
come up and say "you have been disconnected 
from the server" and you will be back at the login screen
again. 

https://ibb.co/GRmcwct

![Unlimited Wow you have been disconnected from the server Sept 14 2019](https://user-images.githubusercontent.com/38896397/64912124-0075fd00-d6e8-11e9-8d7a-c059c2cc4071.jpg)

**Expected behaviour:**

You should be able to link the item to any 
channel in the game. 

**Steps to reproduce the problem:**

1. Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.  
2. Step 2
3. Step 3

I can't provide you the link for this item from wowhead though
because it is a custom item. 

1. Obtain one of the Bronze Gladiator's Totem from a T2 custom instance
2. Try and link said item to any channel such as a party channel
or guild channel and it will log you off.

**Comment by GladiatorUW** [comment]
The linking kick was already fixed a while ago
