### ISSUE TITLE
 [Raise Dead]

### ISSUE THREAD

**Issue by nightbaneftw** [Unlimited-WoW/BugTracker#28]
**Description:**
Alot of bugs

**Current behaviour:**

Alot of bugs

**Expected behaviour:**

Alot of bugs

**Steps to reproduce the problem:**

1. Step 1 pet is supposed to be scale with owner's stats(  [Summon Gargoyle] needs to scale aswell )
2. Step 2 pet is supposed to start with 100 energy
3. Step 3 pet is supposed to reset his cooldowns on spawn
4. step 4 pet is missing 90% AOE damage reduciton (   [Summon Gargoyle] needs to scale aswell ) 
5. step 5 pet needs to have atleast 500m and good resists so it doesnt die in 1 hit
6. step 6 many more

**Comment by CreedUW** [comment]
Requires c++ dev
