### ISSUE TITLE
 [Anti-Magic Zone] is bugged

### ISSUE THREAD

**Issue by nightbaneftw** [Unlimited-WoW/BugTracker#29]
**Description:**
 [Anti-Magic Zone] is bugged and doesnt absorb any damage

**Current behaviour:**
 [Anti-Magic Zone] is bugged and doesnt absorb any damage

**Expected behaviour:**
 [Anti-Magic Zone] needs to be fixed and absorb for example 500m
**Steps to reproduce the problem:**

1. Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.  
2. Step 2
3. Step 3

**Comment by CreedUW** [comment]
Requires c++ dev
