### ISSUE TITLE
izj 1 removal/fixes 

### ISSUE THREAD

**Issue by izjgod** [Unlimited-WoW/BugTracker#3]
disable the meta gems with "reduce Snare/root duration by 10%
"Fix resilience on donor gear on multipie classes? paladins donor gear 100, resilience each item
"remove. free action potion.restorative potion.living action potion, sheen of zanzan/potion of curing/purification potion"
"add Speed 100% wsg effect /zerker / healing multipie places at starting area, and instance tier 1 - 2- 3"
"change Spawn point to Tier 1 Area "add npc for starter" put sanctuary on the place"
"make all new players Spawn with Starter Gear" with starter bags in main bag" and teleporter/graccu's mince meat fruitcake"

"add up to 1.000 total all resistances for Holy resistance ON gear/Disable paladins spell penetrate "
"add new items only for paladins Healer Speller offset/jewelery Without spell Penertate"
"make speller items Class restricted"
"melee items spell restricted for Higer tiers"
"remove Shirt of the yogg-slayer It having more health than best in slot tier 12 shirt,
"vip Rings/trinket Add 1 more meta gem instead of 2x meta gems, making them worse than tier 13"
"add vip shirt/tabard/neck/Cloak"
"All pets needs Rescaling "dk/ghoul/army of the dead/worms/gorgoly,- mage, water elements/mirrors/,-hunter Pets needs higer health And Damage taken reduced,
/druid,- Treats,- shaman Feral spirit,- priste, Shadowfiend,- warlocks /imp/voidwalker/succbucs/felhunter/felguard,-" and other pets, most of them needs
fixed resilience / more armore / Damage reduce taken from players, and slightly buffed dmg on all pets by 15%"

**Comment by boykevink** [comment]
did you just copy this from the first issue you posted?

**Comment by izjgod** [comment]
iv just made it smaller so its possible to close the post when it gets fixed
