### ISSUE TITLE
lifestealing enchant

### ISSUE THREAD

**Issue by nightbaneftw** [Unlimited-WoW/BugTracker#30]
**Description:**

lifestealing enchant scales with spell power and makes people immortal and specially in the dungeons people can pull alot of mobs and dont die, cuz of the damage and heals from the enchant

**Current behaviour:**

lifestealing enchant scales with spell power 

**Expected behaviour:**

lifestealing enchant to dont scale with spell power 

**Steps to reproduce the problem:**
https://wotlk.evowow.com/?item=38871

**Comment by GladiatorUW** [comment]
We disabled it.
