### ISSUE TITLE
Cooking Recipes Shoveltusk Soup and Succulent Orca Stew

### ISSUE THREAD

**Issue by thereporter42** [Unlimited-WoW/BugTracker#30]
**Description:**

When you are buying the recipe for the Shoveltusk Soup 
and the Succulent Orca Stew it won't actually learn the 
recipe even though your skill is high enough. 

What it appears to be doing is thinking it is the actual
item and not the recipe.  Because when I am trying to click
on the item it is saying "you are too full to eat any more" 

in order to get it to say that you will have to click on the recipe 
a few times. 

https://www.wowhead.com/item=34126/recipe-shoveltusk-soup
https://www.wowhead.com/item=39692/recipe-succulent-orca-stew

Screenshots of the item can be seen at 
https://ibb.co/vQHqFdV
https://ibb.co/3yTrGss

**Current behaviour:**

Won't let you use the recipe instead it thinks you are
eating the item and not trying to use the recipe. 

Tell us what happens.

can't learn the recipe instead it thinks
it is eating the item when it isn't it is supposed
to be the recipe. 

**Expected behaviour:**

Should be able to learn both of these recipes from the 
guy in the mall called Books Cooking (Recipe) next to the cooking 
item vendor. 

Tell us what should happen instead.

**Steps to reproduce the problem:**

1. Go to the NPC in the mall on the upper level of the ship where
all the materials are and where you buy the books. 

2. Buy the two recipes for Recipe: Succulent Orca Stew and for the Shoveltusk Soup from the book vendor. 

3. Right click on the book and try and use it multiple times (click like 6 - 7 times)

4. You won't be learning the recipe and eventually it will say you are too full
to eat any more and the recipe will still be in your inventory.  This is 
definitely a bug. 

https://www.wowhead.com/item=34126/recipe-shoveltusk-soup
https://www.wowhead.com/item=39692/recipe-succulent-orca-stew

![Unlimted-Wow Succulent Orca Stew](https://user-images.githubusercontent.com/38896397/65825482-a7a07b80-e234-11e9-93fc-9c88dcb8e980.jpg)

![Unlimted-Wow Shoveltusk Soup Recipe Sept 28 2019](https://user-images.githubusercontent.com/38896397/65825487-aff8b680-e234-11e9-8e71-7be6adb55d93.jpg)

**Comment by GladiatorUW** [comment]
![image](https://user-images.githubusercontent.com/31390127/163727216-39b2cb3f-f570-4ad2-b815-2da26ec3e362.png)
