### ISSUE TITLE
Guile of Gorefiend is bugged

### ISSUE THREAD

**Issue by nightbaneftw** [Unlimited-WoW/BugTracker#31]
**Description:**

Guile of Gorefiend is bugged and doesnt make Icebound Fortitude 18 sec

**Current behaviour:**

Icebound Fortitude stays 12 sec

**Expected behaviour:**

Icebound Fortitude needs to be 18 sec

**Steps to reproduce the problem:**

1. Step check ibf - 12 sec 
2. Step 2 put 3 points in https://wotlk.evowow.com/?spell=50191
3. Step 3 ibf - 12 sec

**Comment by CreedUW** [comment]
Icebound spell has been changed so this talent wont work
