### ISSUE TITLE
Vampiric blood has 2 min cd

### ISSUE THREAD

**Issue by nightbaneftw** [Unlimited-WoW/BugTracker#32]
**Description:**

Vampiric blood has 2 min cd instead 1 min cd

**Current behaviour:**

Vampiric blood has 2 min cd 

**Expected behaviour:**

Vampiric blood needs to have 1 min cd

**Steps to reproduce the problem:**

1. Step 1 get https://wotlk.evowow.com/?spell=55233
2. Step 2 use the spell
3. Step 3 2 min cd instead 1 min cd

**Comment by CreedUW** [comment]
Cannot change cooldown
