### ISSUE TITLE
lifestealing enchant don't work

### ISSUE THREAD

**Issue by tsvyatko** [Unlimited-WoW/BugTracker#33]
**Description:**

lifestealing enchant don't work after last update of the server
**Current behaviour:**

Tell us what happens.

lifestealing enchant don't work after last update of the server. I use scroll a few times and delete my cache folder but no effect. 

Tell us what should happen instead.

lifestealing enchant it's a game changer and should work popper.  
1. Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.  
2. Step 2
3. Step 3

**Comment by GladiatorUW** [comment]
We disabled it.
