### ISSUE TITLE
Missing VIP Token & Issues with Character Loading from Cache

### ISSUE THREAD

**Issue by zweetdk** [Unlimited-WoW/BugTracker#34]
**Description:**
PURCHASED VIP, NO TOKEN GIVEN, DELETED CACHE----CANNOT LOG ON MY CHARACTER

Please assist
Description of the problem or issue here.

**Current behaviour:**

Tell us what happens.
I purchased a VIP token, last night. I attempted to activate my account, but for some reason I continue to be told that i do not have the appropriate token. I have cleared my cache and re-downloaded the patch, as instructed to do on the website. 

When I delete the cache my character is no longer accessible. I have deleted my cache last night 4 times and re-patched 4 times.....to no avail. My character is still unable to log in but every other character on the account logs in just fine. 
**Expected behaviour:**

Tell us what should happen instead.

**Steps to reproduce the problem:**

1. Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.  
2. Step 2 dont know.... other people have experienced this issue and told me to reach out to GM's but there was no resolution overall... except to use old Cache files
3. Step 3

**Comment by ahmad2ssss** [comment]
this server is good but gm of it sleeping
