### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by alvariclank** [Unlimited-WoW/BugTracker#35]
**Description:**

Can't connect to the game

**Current behaviour:**

Whenever I open WoW.exe, it starts without any problem, but when I enter my credentials and try to log in my account, it says "system unavailable - please try again later". Point out that I downloaded the full game from torrent (with all patches and fixes). When I start the game, the selected realm is "DeV test realm" or something like it

**Expected behaviour:**

I should get to my character list but there is no way I can do it.

**Steps to reproduce the problem:**

1. Open wow.exe  
2. Type in my credentials
3. Cry

**Comment by GladiatorUW** [comment]
Please follow this guide; http://unlimited-wow.com/page/connect
