### ISSUE TITLE
WoW error, lost one character, unable to read the game (only one character)

### ISSUE THREAD

**Issue by fullrecen** [Unlimited-WoW/BugTracker#36]
World of WarCraft (build 12340)

Exe:      C:\Program Files (x86)\World Of Warcraft\WoW 3.3.5a\WoW La Ira del Rey Lich King\Wow.exe
Time:     Oct 21, 2019  5:01:14.316 PM
User:     Mis Documentos
Computer: PC-13
------------------------------------------------------------------------------

This application has encountered a critical error:

Espacio de almacenamiento insuficiente para procesar este comando.

Program:	C:\Program Files (x86)\World Of Warcraft\WoW 3.3.5a\WoW La Ira del Rey Lich King\Wow.exe
Object:	DBCACHECALLBACK (.?AUDBCACHECALLBACK@@)

Requested 32 bytes of memory

WoWBuild: 12340
Realm: Unlimited WoW [149.202.64.96:9150]
Local Zone: Cala del Aparejo Perdido, Tanaris
Local Player: Konamy, 0000000000042C18, (-8088.33,-5243.32,1.95662)
Total lua memory: 14667KB
Current Addon: (null)
Current Addon function: UNKNOWN
Current Addon object: (null)
Add Ons: Bagnon Bagnon_Forever Bagnon_Tooltips 
Settings: 
SET locale "esES"
SET realmList "logon.unlimited-wow.com"
SET realmname "Unlimited WoW"
SET hwDetect "0"
SET gxWindow "1"
SET gxResolution "1176x664"
SET gxRefresh "60"
SET gxMultisampleQuality "0.000000"
SET gxFixLag "0"
SET videoOptionsVersion "3"
SET movie "0"
SET checkAddonVersion "0"
SET mouseSpeed "1"
SET Gamma "1.000000"
SET readTOS "1"
SET readEULA "1"
SET readTerminationWithoutNotice "1"
SET showToolsUI "1"
SET accounttype "LK"
SET Sound_OutputDriverName "System Default"
SET Sound_MusicVolume "0.40000000596046"
SET Sound_AmbienceVolume "0.60000002384186"
SET farclip "727"
SET specular "1"
SET groundEffectDensity "24"
SET projectedTextures "1"
SET gameTip "1"

----------------------------------------
               GxInfo
----------------------------------------
GxApi: D3D9
Adapter Count: 1

Adapter 0 (primary):
  Driver: nvd3dum.dll
  Version: 23.21.0013.8800
  Description: NVIDIA GeForce GT 1030
  DeviceName: \\.\DISPLAY1

------------------------------------------------------------------------------

----------------------------------------
    Stack Trace (Manual)
----------------------------------------

Address  Frame    Logical addr  Module

Showing 1/1 threads...

--- Thread ID: 8012 [Current Thread] ---
0076E57E 0382FDB8 0001:0036D57E C:\Program Files (x86)\World Of Warcraft\WoW 3.3.5a\WoW La Ira del Rey Lich King\Wow.exe
0067CB30 0382FDDC 0001:0027BB30 C:\Program Files (x86)\World Of Warcraft\WoW 3.3.5a\WoW La Ira del Rey Lich King\Wow.exe
006DE62C 0382FE1C 0001:002DD62C C:\Program Files (x86)\World Of Warcraft\WoW 3.3.5a\WoW La Ira del Rey Lich King\Wow.exe
0067CD41 0382FE48 0001:0027BD41 C:\Program Files (x86)\World Of Warcraft\WoW 3.3.5a\WoW La Ira del Rey Lich King\Wow.exe
006354E3 0382FE58 0001:002344E3 C:\Program Files (x86)\World Of Warcraft\WoW 3.3.5a\WoW La Ira del Rey Lich King\Wow.exe
0063202E 0382FE7C 0001:0023102E C:\Program Files (x86)\World Of Warcraft\WoW 3.3.5a\WoW La Ira del Rey Lich King\Wow.exe
006324CE 0382FEAC 0001:002314CE C:\Program Files (x86)\World Of Warcraft\WoW 3.3.5a\WoW La Ira del Rey Lich King\Wow.exe
00633568 0382FED4 0001:00232568 C:\Program Files (x86)\World Of Warcraft\WoW 3.3.5a\WoW La Ira del Rey Lich King\Wow.exe
00464BF3 0382FF18 0001:00063BF3 C:\Program Files (x86)\World Of Warcraft\WoW 3.3.5a\WoW La Ira del Rey Lich King\Wow.exe
0047DC4C 0382FF40 0001:0007CC4C C:\Program Files (x86)\World Of Warcraft\WoW 3.3.5a\WoW La Ira del Rey Lich King\Wow.exe
0047F29A 0382FF94 0001:0007E29A C:\Program Files (x86)\World Of Warcraft\WoW 3.3.5a\WoW La Ira del Rey Lich King\Wow.exe
0047F2E1 0382FFAC 0001:0007E2E1 C:\Program Files (x86)\World Of Warcraft\WoW 3.3.5a\WoW La Ira del Rey Lich King\Wow.exe
0040B7D8 0382FFB4 0001:0000A7D8 C:\Program Files (x86)\World Of Warcraft\WoW 3.3.5a\WoW La Ira del Rey Lich King\Wow.exe
75E9C032 0382FFEC 0001:0002C032 C:\Windows\syswow64\kernel32.dll
75E9BFEA 0382FFFC 0001:0002BFEA C:\Windows\syswow64\kernel32.dll

----------------------------------------
    Stack Trace (Using DBGHELP.DLL)
----------------------------------------

****  Couldn't load DBGHELP.DLL, error: 8

----------------------------------------
    Loaded Modules
----------------------------------------

DBG-MODULE<00400000 009FD000 "Wow.exe" "Wow.pdb" 0 {8805d059-f6a3-4565-a646aa69736d4efe} 1 1277448958>
DBG-MODULE<10000000 00069000 "DivxDecoder.dll" "" 0 {00000000-0000-0000-0000000000000000} 0 1076466304>
DBG-MODULE<69120000 00030000 "wdmaud.drv" "wdmaud.pdb" 0 {f232d0b4-9257-4d79-92d5805bef84a01e} 2 1290254886>
DBG-MODULE<69150000 000A6000 "jscript.dll" "jscript.pdb" 0 {02efc204-b8a3-4c27-8e9543faa4ee8d4a} 2 1432350302>
DBG-MODULE<69200000 0020E000 "nvspcap.dll" "nvspcap.pdb" 0 {38f935ce-0195-4d9e-80ae12e379c4045a} 3 1520947294>
DBG-MODULE<69410000 003C8000 "nvapi.dll" "nvapi.pdb" 0 {e7089dbb-441f-4dc9-8e6c674dff329d0c} 1 1507836178>
DBG-MODULE<697E0000 00E4E000 "nvd3dum.dll" "nvd3dum.pdb" 0 {836f70ff-5542-4730-82352936b194bc24} 1 1507836347>
DBG-MODULE<6A630000 001C3000 "d3d9.dll" "d3d9.pdb" 0 {f55aeb50-462b-473f-9733515dc6532daf} 2 1290254259>
DBG-MODULE<6A810000 00036000 "AUDIOSES.DLL" "AudioSes.pdb" 0 {10157340-d040-4212-b80b2016e1046969} 2 1465917686>
DBG-MODULE<6A850000 00039000 "MMDevApi.dll" "MMDevAPI.pdb" 0 {941e45a6-3e8f-457d-90ce29cc508c34b9} 2 1290254482>
DBG-MODULE<6A890000 000CC000 "nvSCPAPI.dll" "NvSCPAPI.pdb" 0 {c66a4c6f-86bb-4aea-932fddf8a22b21bb} 1 1507838142>
DBG-MODULE<6A960000 00065000 "nvStereoApiI.dll" "nvStereoApiI.pdb" 0 {781827ec-a64f-408d-93b3fd36dfb2059b} 1 1507838161>
DBG-MODULE<6A9D0000 00079000 "mscms.dll" "mscms.pdb" 0 {dcc29523-d3bc-4cd4-a76aef0e615bb152} 2 1486656939>
DBG-MODULE<6AA50000 0007A000 "AcSpecfc.DLL" "AcSpecfc.pdb" 0 {0350c126-8780-4ea1-973adbfa3a52073b} 2 1446140406>
DBG-MODULE<6AAD0000 000E7000 "DDRAW.dll" "ddraw.pdb" 0 {497dbeef-b385-4f24-bc6a468137860ada} 2 1247533496>
DBG-MODULE<6CB50000 00004000 "api-ms-win-downlevel-shlwapi-l2-1-0.dll" "api-ms-win-downlevel-shlwapi-l2-1-0.pdb" 0 {75dcf1b0-d479-47cb-b4ea48bd45eba5d0} 1 1358111467>
DBG-MODULE<6DBA0000 00007000 "midimap.dll" "midimap.pdb" 0 {49f76fa5-3b85-4e54-a748a2b4301471b6} 2 1247533700>
DBG-MODULE<6DBF0000 00013000 "dwmapi.dll" "dwmapi.pdb" 0 {3478583a-5a88-473e-a647096a55e52c2a} 2 1436463421>
DBG-MODULE<6DD30000 00008000 "msacm32.drv" "msacm32.pdb" 0 {eb29395a-e017-43db-8c5dcb7f5a1350f9} 1 1247533647>
DBG-MODULE<6DD40000 00007000 "AVRT.dll" "avrt.pdb" 0 {a15e148a-cfc7-4f88-a0a6daf71cc91647} 2 1247533464>
DBG-MODULE<6EA40000 000C8000 "OPENGL32.dll" "opengl32.pdb" 0 {d6a5e50a-cc5c-4af5-9ff7b7b387ca4a2a} 2 1247533787>
DBG-MODULE<6EB40000 00011000 "jsproxy.dll" "JSPROXY.pdb" 0 {60b95386-56a4-4ec5-821d456e3b4c5559} 2 1432350546>
DBG-MODULE<6EC60000 00006000 "d3d8thk.dll" "d3d8thk.pdb" 0 {d9c3a335-615f-448e-a0b012d76716e6b7} 2 1247533480>
DBG-MODULE<6EC90000 00004000 "ksuser.dll" "ksuser.pdb" 0 {b8a733a4-3d47-4e9d-9a788ed035b1bfd3} 2 1449611605>
DBG-MODULE<6ECA0000 00030000 "DINPUT8.dll" "dinput8.pdb" 0 {ca86b91a-9619-4907-8e07314413ffe1dd} 2 1247533505>
DBG-MODULE<6EF40000 00006000 "DCIMAN32.dll" "dciman32.pdb" 0 {ca43ced2-0e96-4317-8a7082542cb86a44} 2 1494612205>
DBG-MODULE<6EF50000 00022000 "GLU32.dll" "glu32.pdb" 0 {2c6b6170-dfa8-4c3e-8ce7ef5d4408ce74} 2 1247533535>
DBG-MODULE<70120000 00004000 "api-ms-win-downlevel-advapi32-l2-1-0.dll" "api-ms-win-downlevel-advapi32-l2-1-0.pdb" 0 {dd3636f5-9f67-41cb-80dee0abeaef8c11} 1 1358111566>
DBG-MODULE<70130000 00008000 "Secur32.dll" "secur32.pdb" 0 {dee882eb-dc2b-4b19-8d28f497fddac70f} 2 1505315393>
DBG-MODULE<70190000 00010000 "aswhook.dll" "aswhook.pdb" 0 {b1b56d0a-baba-4c15-9582d06891050e8b} 1 1551098984>
DBG-MODULE<70220000 00006000 "rasadhlp.dll" "rasadhlp.pdb" 0 {9c177d0e-6fd1-4d28-bae05d9757e8182f} 2 1247533782>
DBG-MODULE<70260000 00014000 "MSACM32.dll" "msacm32.pdb" 0 {3d318d5e-38c5-4502-b64578f0710a510f} 2 1247533646>
DBG-MODULE<70940000 00038000 "fwpuclnt.dll" "fwpuclnt.pdb" 0 {1f1e56c7-fd0a-45b0-9a523fa4f0944f63} 2 1381543334>
DBG-MODULE<70D30000 00009000 "HID.DLL" "hid.pdb" 0 {015645ef-10de-49b0-84ee745a3fdc0f8d} 2 1247533548>
DBG-MODULE<70DA0000 000F5000 "PROPSYS.dll" "propsys.pdb" 0 {d0eda507-e53d-4579-a337f875012d7b48} 2 1290254723>
DBG-MODULE<70FA0000 00024000 "WLIDNSP.DLL" "wlidNSP.pdb" 0 {15804d48-f46d-4c46-91d1f3da4c472364} 1 1250620100>
DBG-MODULE<70FD0000 00008000 "winrnr.dll" "winrnr.pdb" 0 {45f8b97b-1285-48d7-88289c58e8c5b3ca} 2 1247533892>
DBG-MODULE<70FE0000 00012000 "pnrpnsp.dll" "pnrpnsp.pdb" 0 {d02619bd-04db-444d-9215d3ce9d69f106} 2 1247533814>
DBG-MODULE<71000000 00010000 "napinsp.dll" "NapiNSP.pdb" 0 {35d1fb44-6b06-4c3c-84108202e55b284a} 2 1247533677>
DBG-MODULE<71010000 00010000 "NLAapi.dll" "nlaapi.pdb" 0 {35699ef5-3c27-4dc3-9f171ec595e161b6} 2 1417837660>
DBG-MODULE<71050000 00044000 "DNSAPI.dll" "dnsapi.pdb" 0 {4b77ba91-498a-432f-8dd6e52085c4c423} 2 1299130163>
DBG-MODULE<71110000 00006000 "wship6.dll" "wship6.pdb" 0 {02e45101-e951-429f-85676adfcc0ea72a} 2 1247533910>
DBG-MODULE<71130000 0003C000 "mswsock.dll" "mswsock.pdb" 0 {4cec62ee-dfd0-476b-9c7d90dd228ae55a} 2 1462980008>
DBG-MODULE<71170000 00025000 "powrprof.dll" "powrprof.pdb" 0 {b1f8f66c-cbad-4869-badfd20c1f24ac83} 2 1247533836>
DBG-MODULE<711A0000 00032000 "WINMM.dll" "winmm.pdb" 0 {7afd98fc-aad3-4f6b-8b31a4667c4e2bfc} 2 1290254914>
DBG-MODULE<711E0000 0003B000 "rsaenh.dll" "rsaenh.pdb" 0 {f03813e5-a055-4853-a6bc085c17a3ab35} 2 1247533792>
DBG-MODULE<71E20000 00017000 "CRYPTSP.dll" "cryptsp.pdb" 0 {e0a768b6-3e64-41c7-bde1ee6a5dea57e8} 1 1465917847>
DBG-MODULE<71E50000 00005000 "wshtcpip.dll" "wshtcpip.pdb" 0 {92a92ff2-9357-4b48-9795898561f00719} 2 1247533914>
DBG-MODULE<71E60000 0000E000 "RpcRtRemote.dll" "RpcRtRemote.pdb" 0 {16827eb6-7c58-4e0d-8b17b60d76b2b0ce} 2 1290246447>
DBG-MODULE<72E20000 00012000 "MPR.dll" "mpr.pdb" 0 {1408743d-4222-4025-a49e02a79ce7190a} 2 1247533622>
DBG-MODULE<72ED0000 00021000 "ntmarta.dll" "ntmarta.pdb" 0 {654e30bb-ae86-4799-893af657fea77172} 2 1247533801>
DBG-MODULE<73080000 00246000 "msi.dll" "msi.pdb" 0 {ef6f9dd7-6903-4066-922bd014dc2c06c0} 2 1478708361>
DBG-MODULE<734D0000 00003000 "api-ms-win-core-synch-l1-2-0.DLL" "api-ms-win-core-synch-l1-2-0.pdb" 0 {6c200a34-ce63-413c-990a6e74ad9bdc82} 1 1484374117>
DBG-MODULE<73780000 0019E000 "Comctl32.dll" "comctl32.pdb" 0 {6212f637-2dff-46b3-89b1997a0e79c1f5} 2 1429898053>
DBG-MODULE<745F0000 0004C000 "apphelp.dll" "apphelp.pdb" 0 {086332a0-927f-42d1-89abea071ee447a1} 2 1446140464>
DBG-MODULE<74810000 00007000 "WINNSI.DLL" "winnsi.pdb" 0 {1bfa11fa-e340-47e1-adff9a066d07b15b} 2 1502432411>
DBG-MODULE<74820000 0001C000 "IPHLPAPI.DLL" "iphlpapi.pdb" 0 {f162d2e1-37ed-4297-8bf38c99aee2daab} 2 1290254425>
DBG-MODULE<74850000 00084000 "COMCTL32.dll" "comctl32v582.pdb" 0 {fac96c8d-edcb-45bb-b7c7e35ee4e45c4c} 2 1429898210>
DBG-MODULE<748F0000 00009000 "VERSION.dll" "version.pdb" 0 {52234e5c-7ec4-4646-b62d56357b2c9487} 2 1247533867>
DBG-MODULE<74A70000 0000C000 "CRYPTBASE.dll" "cryptbase.pdb" 0 {d341dd50-7e02-4b1e-b79c639c360d4a16} 2 1505313973>
DBG-MODULE<74A80000 00060000 "SspiCli.dll" "wsspicli.pdb" 0 {787b6894-55de-44c5-922463562938bff1} 1 1505315350>
DBG-MODULE<74AE0000 0009D000 "USP10.dll" "usp10.pdb" 0 {f3dcdb66-ac78-4318-b4dc37c0fbea1ba6} 1 1502896249>
DBG-MODULE<74B80000 00004000 "api-ms-win-downlevel-shlwapi-l1-1-0.dll" "api-ms-win-downlevel-shlwapi-l1-1-0.pdb" 0 {dc8c3e81-3e5b-4491-afcb375f0f7ce050} 1 1358111823>
DBG-MODULE<74B90000 00003000 "api-ms-win-downlevel-normaliz-l1-1-0.dll" "api-ms-win-downlevel-normaliz-l1-1-0.pdb" 0 {5402f635-52f3-4e26-a727bf0c479713ee} 1 1358111822>
DBG-MODULE<74BA0000 000AC000 "msvcrt.dll" "msvcrt.pdb" 0 {f1d253f9-555c-46df-8076400a52b3a929} 2 1324021538>
DBG-MODULE<74C50000 00004000 "api-ms-win-downlevel-user32-l1-1-0.dll" "api-ms-win-downlevel-user32-l1-1-0.pdb" 0 {02cb0348-17b4-4abb-99da042a6008fe6c} 1 1358111481>
DBG-MODULE<74C60000 000F0000 "RPCRT4.dll" "wrpcrt4.pdb" 0 {e40a69c3-e600-4a29-93ba9b4684586e5c} 2 1505315350>
DBG-MODULE<74D50000 00004000 "api-ms-win-downlevel-ole32-l1-1-0.dll" "api-ms-win-downlevel-ole32-l1-1-0.pdb" 0 {652bbf24-4e0d-4471-959c6080260743b7} 1 1358111468>
DBG-MODULE<74D60000 00012000 "DEVOBJ.dll" "devobj.pdb" 0 {583f4457-964d-46ca-8c36ed4903be6aa2} 2 1306232957>
DBG-MODULE<74D80000 00027000 "CFGMGR32.dll" "cfgmgr32.pdb" 0 {e4c73e93-b825-413f-99e80ba656c48317} 2 1306232913>
DBG-MODULE<74DB0000 00005000 "api-ms-win-downlevel-advapi32-l1-1-0.dll" "api-ms-win-downlevel-advapi32-l1-1-0.pdb" 0 {815d3737-568d-4305-842320735da06f72} 1 1358111802>
DBG-MODULE<74DC0000 00060000 "IMM32.dll" "wimm32.pdb" 0 {35dd4069-eb2a-43bf-869d6e311fad0945} 2 1290254931>
DBG-MODULE<74E20000 00232000 "iertutil.dll" "iertutil.pdb" 0 {b176fd10-07e7-46b3-aa76a040cd18c205} 2 1432350632>
DBG-MODULE<75060000 0014A000 "urlmon.dll" "urlmon.pdb" 0 {557994b1-0d8b-4208-bcf0395678aa4650} 2 1432347392>
DBG-MODULE<751B0000 00045000 "WLDAP32.dll" "wldap32.pdb" 0 {b3afebe0-e648-46fe-87eaac5b2cd2d6a3} 2 1502432442>
DBG-MODULE<75200000 0019D000 "SETUPAPI.dll" "setupapi.pdb" 0 {c6b7cc38-0fcd-42c2-9edb1b61757dfd92} 2 1290254809>
DBG-MODULE<753A0000 00091000 "OLEAUT32.dll" "oleaut32.pdb" 0 {6851eea1-91f4-4b85-abb56ddda78abd7c} 2 1492441960>
DBG-MODULE<75440000 0000C000 "MSASN1.dll" "msasn1.pdb" 0 {003d5f0e-2480-4b20-953a7a021b52fc32} 2 1290254537>
DBG-MODULE<75450000 00019000 "sechost.dll" "sechost.pdb" 0 {2c99b7b1-394e-4c64-b66de258b63c07f5} 1 1432576740>
DBG-MODULE<75470000 0002F000 "WINTRUST.dll" "wintrust.pdb" 0 {8a700ca4-210a-4bbc-87f92370010908d1} 2 1492010814>
DBG-MODULE<754A0000 00017000 "USERENV.dll" "userenv.pdb" 0 {fd47f512-75f8-4fca-aa6071cb11cc4ab8} 2 1290254888>
DBG-MODULE<754C0000 000A1000 "ADVAPI32.dll" "advapi32.pdb" 0 {9d2559de-439d-4f27-a336602b9098c936} 2 1505315341>
DBG-MODULE<75570000 000CD000 "MSCTF.dll" "msctf.pdb" 0 {b377c450-ede1-4d4c-aed26e970740059c} 2 1505315404>
DBG-MODULE<75640000 00004000 "api-ms-win-downlevel-version-l1-1-0.dll" "api-ms-win-downlevel-version-l1-1-0.pdb" 0 {204b81c3-3a4d-4100-a32de3be94935e66} 1 1358111467>
DBG-MODULE<75650000 00057000 "shlwapi.DLL" "shlwapi.pdb" 0 {e128b1ce-e2eb-438c-8646e6967118f33e} 2 1290254818>
DBG-MODULE<756B0000 001E4000 "WININET.dll" "wininet.pdb" 0 {49751b1a-ead6-4774-9ae9b8cb573529e3} 2 1432347617>
DBG-MODULE<75900000 00047000 "KERNELBASE.dll" "wkernelbase.pdb" 0 {dea6e346-5410-454b-8cf1fb59a95ee0bd} 1 1505315515>
DBG-MODULE<75950000 00090000 "GDI32.dll" "wgdi32.pdb" 0 {7779fd51-f1c9-4e08-9faed5e01e3c955d} 2 1504883406>
DBG-MODULE<759E0000 00121000 "CRYPT32.dll" "crypt32.pdb" 0 {7600f7b8-52f6-4b96-b46a11656a195316} 2 1492010867>
DBG-MODULE<75B10000 00006000 "NSI.dll" "nsi.pdb" 0 {d4f9fbf1-4678-4c50-b403eaa659593de5} 2 1502432485>
DBG-MODULE<75BB0000 00003000 "normaliz.DLL" "normaliz.pdb" 0 {9481804b-b4fd-4703-ae6ae76f8b99b476} 1 1247533780>
DBG-MODULE<75BC0000 00005000 "PSAPI.DLL" "psapi.pdb" 0 {a895a052-f325-481b-9e2da00a29e8d5df} 2 1247533774>
DBG-MODULE<75C00000 00100000 "USER32.dll" "wuser32.pdb" 0 {438bb768-e243-4151-ba04e6929c010052} 2 1247533884>
DBG-MODULE<75D00000 0015D000 "ole32.dll" "ole32.pdb" 0 {215568f9-dcc9-44e1-80513e1b14df5928} 2 1502432393>
DBG-MODULE<75E60000 00110000 "kernel32.dll" "wkernel32.pdb" 0 {d658cf17-d7b2-4b5c-81ba1b32c4bba0f2} 2 1505315514>
DBG-MODULE<75F70000 0000B000 "profapi.dll" "profapi.pdb" 0 {ca045ca9-e5c7-4d89-9b90e776b38a18b3} 2 1247526721>
DBG-MODULE<75F80000 00083000 "CLBCatQ.DLL" "CLBCatQ.pdb" 0 {00a720c7-9bac-4022-95b6ebdc14725718} 2 1247533489>
DBG-MODULE<76010000 00035000 "WS2_32.dll" "ws2_32.pdb" 0 {f2ef0aea-45aa-413a-8f4de1bdd42cc19d} 2 1462979980>
DBG-MODULE<76050000 00C4C000 "SHELL32.dll" "shell32.pdb" 0 {f57374e9-0888-43fd-bb8288bac1c1bbba} 2 1502809856>
DBG-MODULE<76CA0000 0007B000 "COMDLG32.dll" "comdlg32.pdb" 0 {96bc483c-dff0-4d1a-afe462f093b954ec} 2 1290254381>
DBG-MODULE<770F0000 0000A000 "LPK.dll" "wlpk.pdb" 0 {b36b83f3-3e75-4183-b11ef6d06056512f} 1 1494612200>
DBG-MODULE<77120000 00180000 "ntdll.dll" "wntdll.pdb" 0 {2babfaa0-5142-4da8-a3f0f3736f9bb7a1} 2 1505315350>

----------------------------------------
    Memory Dump
----------------------------------------

Stack: 1024 bytes starting at (ESP = 0382FCB8)

* = addr                            **                                *       
0382FCB0: F6 E6 77 00  B8 FC 82 03  0C 25 00 00  02 00 00 00  ..w......%......
0382FCC0: F6 E6 77 00  B8 FC 82 03  CC FC 82 03  FC FC 82 03  ..w.............
0382FCD0: 65 23 77 00  01 00 6E 00  B0 10 77 00  0C 25 00 00  e#w...n...w..%..
0382FCE0: 03 00 00 00  00 00 00 00  28 D8 C5 00  20 00 00 00  ........(... ...
0382FCF0: 00 00 00 00  20 FD 82 03  42 00 00 00  A0 FD 82 03  .... ...B.......
0382FD00: 21 E5 76 00  08 00 00 00  8C 5D AD 00  FE FF FF FF  !.v......]......
0382FD10: 20 FD 82 03  00 00 00 00  01 00 00 00  11 11 11 11   ...............
0382FD20: 52 65 71 75  65 73 74 65  64 20 33 32  20 62 79 74  Requested 32 byt
0382FD30: 65 73 20 6F  66 20 6D 65  6D 6F 72 79  00 00 00 00  es of memory....
0382FD40: A0 FD 82 03  84 FD 82 03  FC 69 41 00  00 00 F3 02  .........iA.....
0382FD50: 08 00 00 00  55 6A 41 00  E3 FF 90 C3  20 00 00 00  ....UjA..... ...
0382FD60: 30 D8 C5 00  28 D8 C5 00  00 00 00 00  A0 FD 82 03  0...(...........
0382FD70: DC DD 40 00  26 00 00 00  A0 FD 82 03  88 DF 40 00  ..@.&.........@.
0382FD80: 08 00 00 00  00 00 00 00  0C 00 00 00  72 00 41 00  ............r.A.
0382FD90: 8D 6A 41 00  30 D8 C5 00  20 00 00 00  0C 00 00 00  .jA.0... .......
0382FDA0: B8 FD 82 03  7E E5 76 00  8C 5D AD 00  FE FF FF FF  ....~.v..]......
0382FDB0: 90 E4 6D 00  30 D8 C5 00  DC FD 82 03  30 CB 67 00  ..m.0.......0.g.
0382FDC0: 20 00 00 00  8C 5D AD 00  FE FF FF FF  08 00 00 00   ....]..........
0382FDD0: 00 00 00 00  98 32 10 18  24 00 00 00  1C FE 82 03  .....2..$.......
0382FDE0: 2C E6 6D 00  38 91 3B 18  04 FE 82 03  90 E4 6D 00  ,.m.8.;.......m.
0382FDF0: 00 00 00 00  00 00 00 00  30 D8 C5 00  A8 8C 3B 18  ........0.....;.
0382FE00: C0 01 22 51  00 00 00 00  00 00 00 00  12 00 00 00  .."Q............
0382FE10: 18 00 00 00  F0 65 FA 05  03 00 00 00  48 FE 82 03  .....e......H...
0382FE20: 41 CD 67 00  9F A1 00 00  30 01 22 51  00 00 00 00  A.g.....0."Q....
0382FE30: 01 00 00 00  58 00 00 00  94 FE 82 03  90 EC 12 0A  ....X...........
0382FE40: 28 D8 C5 00  9F A1 00 00  58 FE 82 03  E3 54 63 00  (.......X....Tc.
0382FE50: 94 FE 82 03  01 00 00 01  7C FE 82 03  2E 20 63 00  ........|.... c.
0382FE60: 00 00 00 00  58 00 00 00  DB 74 05 00  94 FE 82 03  ....X....t......
0382FE70: E4 78 8D 09  90 EC 12 0A  A8 9C BD 1C  AC FE 82 03  .x..............
0382FE80: CE 24 63 00  DB 74 05 00  58 00 82 03  00 00 00 00  .$c..t..X.......
0382FE90: E0 78 8D 09  24 0E 9E 00  30 D4 6E 1D  00 00 00 00  .x..$...0.n.....
0382FEA0: FF FF FF FF  DD 01 00 00  DD 01 00 00  D4 FE 82 03  ................
0382FEB0: 68 35 63 00  DB 74 05 00  30 D4 6E 1D  DD 01 00 00  h5c..t..0.n.....
0382FEC0: 90 57 B0 03  41 95 AB 00  30 3C 08 0B  01 00 00 00  .W..A...0<......
0382FED0: 18 FF 82 00  18 FF 82 03  F3 4B 46 00  50 58 B0 03  .........KF.PX..
0382FEE0: D9 1F 40 00  00 00 00 00  00 00 00 00  79 0B 48 00  ..@.........y.H.
0382FEF0: 00 00 00 00  00 00 00 00  18 75 05 00  90 57 B0 03  .........u...W..
0382FF00: 30 3C 08 0B  60 F0 88 09  90 57 B0 03  00 00 00 00  0<..`....W......
0382FF10: A0 57 B0 03  01 00 00 00  40 FF 82 03  4C DC 47 00  .W......@...L.G.
0382FF20: 90 57 B0 03  07 00 00 00  00 00 00 00  4E F1 47 00  .W..........N.G.
0382FF30: 00 00 00 00  00 00 00 00  EC FE 1F 00  00 00 00 00  ................
0382FF40: 94 FF 82 03  9A F2 47 00  00 00 00 00  1F 85 2B 3F  ......G.......+?
0382FF50: 00 00 00 00  45 6E 67 69  6E 65 20 31  66 34 63 00  ....Engine 1f4c.
0382FF60: 78 FF 82 03  93 18 91 75  00 00 00 00  C8 1E 9E 00  x......u........
0382FF70: 02 00 00 00  00 00 00 00  E0 50 24 01  00 00 00 00  .........P$.....
0382FF80: E9 F9 13 77  05 0F 91 75  34 21 00 00  00 00 00 00  ...w...u4!......
0382FF90: AC FF 82 03  AC FF 82 03  E1 F2 47 00  00 00 00 00  ..........G.....
0382FFA0: 22 6D 40 00  01 00 00 00  01 00 00 00  B4 FF 82 03  "m@.............
0382FFB0: D8 B7 40 00  EC FF 82 03  32 C0 E9 75  EC FE 1F 00  ..@.....2..u....
0382FFC0: 7A 87 E5 C3  00 00 00 00  00 00 00 00  EC FE 1F 00  z...............
0382FFD0: 00 00 00 00  C0 FF 82 03  00 00 00 00  FF FF FF FF  ................
0382FFE0: F3 48 F1 75  D6 B8 8E B5  00 00 00 00  FC FF 82 03  .H.u............
0382FFF0: EA BF E9 75  F0 FB 24 01  F0 FB 24 01  00 00 00 00  ...u..$...$.....
03830000: 09 43 99 0C  63 31 01 01  EE FF EE FF  00 00 00 00  .C..c1..........
03830010: 10 00 A3 03  10 00 E3 02  00 00 F3 02  00 00 83 03  ................
03830020: 00 02 00 00  40 00 83 03  00 00 A3 03  00 00 00 00  ....@...........
03830030: 01 00 00 00  00 00 00 00  F0 FF A2 03  F0 FF A2 03  ................
03830040: 05 8D 99 CE  6B 31 01 08  2C 00 00 00  00 00 00 00  ....k1..,.......
03830050: 00 00 B0 00  00 00 00 00  00 00 00 00  C0 02 00 00  ................
03830060: 00 00 00 00  00 00 00 0B  00 00 00 00  00 00 00 00  ................
03830070: 00 2C 00 00  00 00 00 00  00 00 00 B0  00 00 00 00  .,..............
03830080: 00 00 00 00  00 C0 02 00  00 00 00 00  00 00 00 00  ................
03830090: 0B 00 00 00  00 00 00 00  00 00 2C 00  00 00 00 00  ..........,.....
038300A0: 00 00 00 00  B0 00 00 00  00 00 00 00  00 00 C0 02  ................
038300B0: 00 00 00 00  00 00 00 00  00 0B 00 00  00 00 00 00  ................

------------------------------------------------------------------------------

======================================================================
Hardware/Driver Information:
Processor:              0x9
Page Size:              4096
Min App Address:        0x10000
Max App Address:        0x7ffeffff
Processor Mask:         0xf
Number of Processors:   4
Processor Type:         8664
Allocation Granularity: 65536
Processor Level:        23
Processor Revision:     257
Os Version:             6.1
Os Service Pack:        1.0

Percent memory used:    53
Total physical memory:  8539017216
Free Memory:            3994066944
Page file:              17076129792
Total virtual memory:   2147352576

**Comment by Delvin1618** [comment]
Hi, I'm going through the same problem. My original character can not be login but I can create new charaters and play with those. What happened with me is I reformated my windows 10 (bootcamp on macbook pro) and redownloaded the wotlk and after that, I couldn't log back on. If possible can someone send me a copy of their cache folder to see with better data I can relog back in
