### ISSUE TITLE
Character bugged

### ISSUE THREAD

**Issue by stefanofv** [Unlimited-WoW/BugTracker#36]
**Description:**

Character bugged

**Current behaviour:**
When i try to log my paladin the game stop working but when i log another character nothing happend and can play that character normal

**Expected behaviour:**

My paladin appear without the transmog that i put him

**Steps to reproduce the problem:**

1. Step 1 Try to enter the world with paladin
2. Step 2 game stop working
3. Step 3 baby rage

**Comment by GladiatorUW** [comment]
Please clear your WDB folder. Contact us ingame if it happens again.
