### ISSUE TITLE
Hunter : Pet LOOT

### ISSUE THREAD

**Issue by Lukyscroot** [Unlimited-WoW/BugTracker#44]
Description: Loot and PET
If my pet kills the NPC and I don't damage it. This is not the NPC loot.
Expected behaviour:  
NPCs can normally loot
Tell us what should happen instead.   
NPCs can normally loot

**Comment by GladiatorUW** [comment]
https://wowwiki-archive.fandom.com/wiki/Hunter_pet

![image](https://user-images.githubusercontent.com/31390127/154296278-58318ee2-b960-4232-82cd-ec81fc49907a.png)
