### ISSUE TITLE
Report abour Gruul Lair 1st Boss

### ISSUE THREAD

**Issue by Kianao** [Unlimited-WoW/BugTracker#45]
**Description:**

Report About Gruul Lair 1st boss

**Current behaviour:**

I Play hunter when i kill the Gruul lair 1st boss, and then i use feign dead for clear mobs. after then boss immediately resp wan .

**Expected behaviour:**

Juz report abug.

**Steps to reproduce the problem:**

1. Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.  
2. Step 2
3. Step 3

**Comment by Morvis1** [comment]
Hello.

I believe that is not a bug actually. "Teammates" of the boss are his part. Whole group is one boss, so you have to kill them all. If rogue will kill one like you did and use vanish, he would respawn as well.

Regards
