### ISSUE TITLE
[Priest][Talent] Improved Devouring Plague does 600 damage

### ISSUE THREAD

**Issue by Callabero** [Unlimited-WoW/BugTracker#52]
Improved devouring plague low damage
Description of the problem or issue here.
Improved devouring plague does way too low instant damage, does like 600-650 only. Tick damage works as intended
Proof: https://imgur.com/a/WeceOAX (see combat log)
**Steps to reproduce the problem:**

1. Step 1 https://imgur.com/a/3wS6UpQ 
2. Step 2 See the peridiotic damage in a 2nd link and charge from that.

Im new to server, hopefully youve got enough info...

Best Regards
Zerthy

**Comment by GladiatorUW** [comment]
The dd of it is intended and not supposed to be boosted.
