### ISSUE TITLE
Diamond Gladiator's Deathknight Sigil requirement

### ISSUE THREAD

**Issue by Luneclaw** [Unlimited-WoW/BugTracker#59]
**Description:**

The captioned quest requires Golden Gladiator's Sigil. But it seems it requires something else with same name.

**Current behaviour:**

Not accepting required item.

**Expected behaviour:**

Accepts items and completes quest.

**Steps to reproduce the problem:**

1. Change the required item to relevant item

**Comment by mecserim** [comment]
Still not working. 

Attached a picture.

Linking the quest gets you disconnected.

![2021-03-12 19_59_58-D3DProxyWindow](https://user-images.githubusercontent.com/60013064/110986276-c255aa00-836d-11eb-8fd0-04eb4b09be8a.png)

**Comment by GladiatorUW** [comment]
Retake the quest :)
