### ISSUE TITLE
Icecrown citadel    

### ISSUE THREAD

**Issue by izjgod** [Unlimited-WoW/BugTracker#6]
gunship boat need clip /guns/faction members on the ship arnt following the ship making it impossible to complete it even with sieg granades
after Deathbringer the teleporte behinde him is not working . 
dreamwalker is not possible to finish, to continue & rotface is untargetable,
no mans land below is nonexsistent, if u fall down with slow fall u wont die.
lich king works like normal, if u can get to him with help of a gamemaster,

but if the team is gona put work into fixing this , i have a suggestion , what about Icecrown citiadel as a tier 14 or later tiers instance?

**Comment by boykevink** [comment]
agreeable

**Comment by CreedUW** [comment]
All old content closed
