### ISSUE TITLE
Zeppelin in Westguard Keep (Howling Fjord) is not giving rides to passengers.

### ISSUE THREAD

**Issue by LionLevik** [Unlimited-WoW/BugTracker#60]
**Description:**

In Howling Fjord, at Westguard Keep there is a tower to which a zeppelin is arriving. It is impossible to stay on the zeppelin once it starts moving. It's not even stopping at the little bridge. Where is this zeppelin going to? Why is it there if it's not functional?

**Current behaviour:**

As soon as the zeppelin moves, it leaves the character behind. It's possible to fly along it, but it will not accept you as a part of itself. 

**Expected behaviour:**

It's expected from any ship or zeppelin to give you a ride. The area of the zeppelin is safe to sit in, will not drop you out or leave without you while you're on it. Maybe it will even load a different zone and take you to a different continent/city. 

**Steps to reproduce the problem:**

1. Step 1 Fly to Westguard Keep as a horde.
2. Step 2 Wait for zeppelin to appear. Sit on the zeppelin when it comes.
3. Step 3 Wait for it to start moving - you will slide off.

**Comment by GladiatorUW** [comment]
The zeppelin has no any purpose, it just flies around in circles
