### ISSUE TITLE
Achievement named What the Eck?

### ISSUE THREAD

**Issue by Bilbou** [Unlimited-WoW/BugTracker#63]
**Description:** Achievement named What the eck? This achievement require you to defeat Gal'darah in Gundrak on Heroic difficulty while under the effects of Eck Residue.

Tell us what happens. Normally you get the debuff when Eck the Ferocious "spit" the spell on you and you get the debuff for 60mins. I did it without gear and bags since you will just evade it but when you finally get it you get the debuff for like 2-3 sec instead of 60min

**Expected behaviour:**

Tell us what should happen instead. Get the debuff for 60min

**Steps to reproduce the problem:**

1. Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.  
2. Step 2
3. Step 3

**Comment by GladiatorUW** [comment]
![image](https://user-images.githubusercontent.com/31390127/154251711-a376cca8-c317-440c-85de-a0296579ba50.png)

Your probably never got hit with the spell since he misses. It is 1 hour, I boosted his level to 255 so he won't miss anymore.
