### ISSUE TITLE
Heroic: Hellfire Ramparts

### ISSUE THREAD

**Issue by Bilbou** [Unlimited-WoW/BugTracker#67]
**Description:**

Description of the problem or issue here. Hellfire Ramparts on heroic mode not working. Even if i have the key i am not able to get in. Hellfire Ramparts on heroic mode is needed to complete achievement named: Heroic: Hellfire Ramparts under Dungeons & Raids -> TBC

**Current behaviour:**

Tell us what happens. Unable to get inside Hellfire Ramparts in heroic mode even if i have the key.

**Expected behaviour:** Should be able to get inside with the key.

Tell us what should happen instead. Should be able to get inside if i have the key to activate it.

**Steps to reproduce the problem:**

1. Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.  
2. Step 2
3. Step 3

**Comment by GladiatorUW** [comment]
Coudln't reproduce it but I removed the requirement for it now.
