### ISSUE TITLE
Warrior disarm bug

### ISSUE THREAD

**Issue by Sazzaok** [Unlimited-WoW/BugTracker#82]
**Description:**

i buy donor head. There you have writen you will have 30sec with that donor head. But i have 50sec cd.. no donor have 40sec cd. I try retalent and i lost scroll of titans grip (50spell tokens)

still have 50sec cd.

Tell us what happens.

I want have that 30 sec with that donor head

Tell us what should happen instead.

fix that bug

1. Step 1 -donor head
2. Step 2 - disarm spell at warrior
3. Step 3

**Comment by GladiatorUW** [comment]
non donor: 
![image](https://user-images.githubusercontent.com/31390127/154073766-f547b301-7c60-4b01-a505-97518b63590c.png)

donor:
![image](https://user-images.githubusercontent.com/31390127/154073806-aae83dc7-7b73-4b90-8b8f-64b3a0cb7554.png)
