### ISSUE TITLE
Broken Account settings

### ISSUE THREAD

**Issue by rcgram** [Unlimited-WoW/BugTracker#86]
**Description:**

The account settings panel is broken.

**Current behaviour:**

Shows raw html code instead of normally loading. EDIT: Not html code, technical info

**Expected behaviour:**

Should open normally.

**Steps to reproduce the problem:**

1. Step 1 Go to UCP .
2. Step 2 Enter account settings.
3. Step 3 Profit.

![image](https://user-images.githubusercontent.com/64264268/142611072-4074230b-415b-4c14-a105-6cead1441e6c.png)

**Comment by GladiatorUW** [comment]
Hello, it works fine to me please try with Google Chrome.
