### ISSUE TITLE
Warlock's "Siphon Life" spell missing

### ISSUE THREAD

**Issue by HubbaBubba420** [Unlimited-WoW/BugTracker#87]
Warlock affliction spell "Siphon Life" appears unavailable but I can't find any info in the bug tracker
to tell me if its been removed on purpose or its just missing.

Can activate it via the talents section but does not show up in spell book and none of the higher tier versions show up in spell book when you see your trainer.

https://www.wowhead.com/spell=63106/siphon-life#:~:text=Siphons%20the%20target's%20life%20essence,30%25%20of%20the%20damage%20done.&text=Requires%20level%2025-,Siphons%20the%20target's%20life%20essence%2C%20dealing%2025%20Shadow%20damage%20over,30%25%20of%20the%20damage%20done.

**Comment by spiderbane** [comment]
Looking at the dates of bugs reported that are still in the game and the fact I was told by a GM my issue would be fixed in 48 hours, a month ago, it's obvious the server owner doesn't care as long as people keep donating.

**Comment by GladiatorUW** [comment]
its a passive talent.
