### ISSUE TITLE
Failed to apply patch

### ISSUE THREAD

**Issue by ClassicTaco** [Unlimited-WoW/BugTracker#88]
Everytime I try to log into the game I get a download for a patch that stays at 0% then it asks me to restart my client to apply it. When I do this I get an error that it failed to apply and that I should reinstall or contact support. I already reinstalled to Im reaching out here.

Not applying patch

apply patch and let me log into the game

**Steps to reproduce the problem:**

1.   Log into game
2.  Downloading at 0%
3. Click ok to restart and get an error message saying failed to apply patch

**Comment by GladiatorUW** [comment]
Please follow our connection guide, do not start the launcher. Use wow.exe instead
