### ISSUE TITLE
website donation

### ISSUE THREAD

**Issue by izjgod** [Unlimited-WoW/BugTracker#9]
iv been hearing from some players that they couldnt donate from thier countery, adding some more donation possibilitys

change way too buy  the donation Gear like putting character first, so its not possible to buy for exmaple full warrior gear on a rogue,  even some players misstakenly bought full donor to his first character created, below checkout button,  such mistakes shouldnt be possible-

**Comment by boykevink** [comment]
yea they probly make that mistake because they cant read english very well...
