### ISSUE TITLE
Gigantic Feast Buff not applying

### ISSUE THREAD

**Issue by HubbaBubba420** [Unlimited-WoW/BugTracker#90]
Upon eating "Gigantic Feast" no effect is applied to character size

ID# 43478

At 15 seconds into eating "this spell is not available to you" is displayed instead of making your character bigger in size

https://www.wowhead.com/item=43478/gigantic-feast

**Comment by GladiatorUW** [comment]
The size increase is disabled, thats why it isn't increasing your size.
