### ISSUE TITLE
Hunter Donor Bow bug

### ISSUE THREAD

**Issue by CorditeRDX** [Unlimited-WoW/BugTracker#92]
**Description:**

actually normal bows gives both spell power and attack power for hunters and both works well for spells but donor bow wont give spell power as well  damage diffrence between donor and normal bow is low very low (compareto other melee weapon and spell staffs)
**Current behaviour:**
i use both normal and donor bows the damage diffrence is blow my mind  these links image from this problem 
i used normal and check damage
i used donor and check damage
i compare both

https://ibb.co/ys0Q5Ts
https://ibb.co/fM0jBB9
https://ibb.co/vv8FwQr

**Expected behaviour:**

donor bows should have spell power and attack power both becus some type of hunter playing is spell some type is physical
**Steps to reproduce the problem:**

**Comment by GladiatorUW** [comment]
This is not a bug, each item has its limits to add spell abilities (the green stuff you see in description). So we can't add more spells to the Donor Bow (which is still better). But if you truely think the dmg diff is very low, I'll check and boost Donor Bow if need.

**Comment by CorditeRDX** [comment]
i think its super low damage actually hunter is one of the weakes class on this server .
also warlock spell lock is buggy and inttrupt wont work its just silence target @GladiatorUW
