### ISSUE TITLE
Item models/Pictures crashing my game

### ISSUE THREAD

**Issue by TracksuitPixen** [Unlimited-WoW/BugTracker#95]
**Description:**
Item models/pictures crashing my game/ cant use weapons
Description of the problem or issue here.
I ahve logged in after like 6-7 months of a pause from the server and now i log back in and i cant attack on my warrior , Look at my bags because if i hold my mouse over a bag my game freezes , same with my gear icons in my character page.
**Current behaviour:**
Still crashing my game
Tell us what happens.
 i cant attack on my warrior , Look at my bags because if i hold my mouse over a bag my game freezes , same with my gear icons in my character page.
**Expected behaviour:**
I SHOULD BE ABLE TO INSPECT THE STATS OF MY GEAR OR EVEN ATTACK PEOPLE!!!
Tell us what should happen instead.

**Steps to reproduce the problem:**

1. Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.  
2. Step 2 Gear: Donor gear for warr
3. Step 3

**Comment by GladiatorUW** [comment]
Hello, make sure you've installed our custom patch correctly. (and the newest one)
