### ISSUE TITLE
Warlock: BUG with demon armor.

### ISSUE THREAD

**Issue by matatan21** [Unlimited-WoW/BugTracker#96]
Demon armor bug when you cast it.

> When you cast Demon Armor(Rank 8) it should give you 26% health generated through spells and effects but when you use it, only shows 20%. Like Demon Skin(Rank 2) which only gives 20%.

  Open Warlock Spellbook>Demonology> Demon Armor(Rank 8) and Demon Skin(rank 2) -Page 1
  
  Screen shots Below
 

![unknown](https://user-images.githubusercontent.com/97418801/148711196-d86dafe1-9140-4ce0-8959-107bf4336b98.png)
![unknown](https://user-images.githubusercontent.com/97418801/148711205-7578d12e-bb3e-4a77-abb8-7c791a0befa8.png)
![unknown](https://user-images.githubusercontent.com/97418801/148711207-4a6749f6-d315-4122-b6ec-b52fa05e79c5.png)
![image](https://user-images.githubusercontent.com/97418801/148711227-28623761-5a79-4a16-bf43-6448bb72123d.png)

**Comment by GladiatorUW** [comment]
Thats just a visual bug, the spell gives 20% which is correct. see; https://wotlkdb.com/?spell=47889
