### ISSUE TITLE
Gruul's lair key

### ISSUE THREAD

**Issue by vladjedd** [Unlimited-WoW/BugTracker#99]
**Description:**

the quest "Gruul's lair key" does not provide the quest completion button

**Current behaviour:**

Even with all the quest requirements ready, I can't deliver the quest

**Expected behaviour:**

Quest completion button available

**Steps to reproduce the problem:**

1. accept the quest
2. Get the quest items
3. try to deliver the quest

**Comment by GladiatorUW** [comment]
Please abandon and retake the quest it must be a cache issue.
